/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq;


import kr.co.common.jooq.tables.Breed;
import kr.co.common.jooq.tables.CommunityComment;
import kr.co.common.jooq.tables.CommunityPost;
import kr.co.common.jooq.tables.Company;
import kr.co.common.jooq.tables.EmailGuest;
import kr.co.common.jooq.tables.EmailVerification;
import kr.co.common.jooq.tables.Event;
import kr.co.common.jooq.tables.FileInfo;
import kr.co.common.jooq.tables.GameScore;
import kr.co.common.jooq.tables.Notice;
import kr.co.common.jooq.tables.Ownership;
import kr.co.common.jooq.tables.Pet;
import kr.co.common.jooq.tables.PetMode;
import kr.co.common.jooq.tables.Role;
import kr.co.common.jooq.tables.Species;
import kr.co.common.jooq.tables.User;
import kr.co.common.jooq.tables.UserVoteCount;
import kr.co.common.jooq.tables.UserVoteCountHistory;
import kr.co.common.jooq.tables.VoteFileInfo;
import kr.co.common.jooq.tables.VoteHistory;
import kr.co.common.jooq.tables.VoteWeekly;
import kr.co.common.jooq.tables.records.BreedRecord;
import kr.co.common.jooq.tables.records.CommunityCommentRecord;
import kr.co.common.jooq.tables.records.CommunityPostRecord;
import kr.co.common.jooq.tables.records.CompanyRecord;
import kr.co.common.jooq.tables.records.EmailGuestRecord;
import kr.co.common.jooq.tables.records.EmailVerificationRecord;
import kr.co.common.jooq.tables.records.EventRecord;
import kr.co.common.jooq.tables.records.FileInfoRecord;
import kr.co.common.jooq.tables.records.GameScoreRecord;
import kr.co.common.jooq.tables.records.NoticeRecord;
import kr.co.common.jooq.tables.records.OwnershipRecord;
import kr.co.common.jooq.tables.records.PetModeRecord;
import kr.co.common.jooq.tables.records.PetRecord;
import kr.co.common.jooq.tables.records.RoleRecord;
import kr.co.common.jooq.tables.records.SpeciesRecord;
import kr.co.common.jooq.tables.records.UserRecord;
import kr.co.common.jooq.tables.records.UserVoteCountHistoryRecord;
import kr.co.common.jooq.tables.records.UserVoteCountRecord;
import kr.co.common.jooq.tables.records.VoteFileInfoRecord;
import kr.co.common.jooq.tables.records.VoteHistoryRecord;
import kr.co.common.jooq.tables.records.VoteWeeklyRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BreedRecord> BREED_PKEY = Internal.createUniqueKey(Breed.BREED, DSL.name("breed_pkey"), new TableField[] { Breed.BREED.BREED_ID }, true);
    public static final UniqueKey<CommunityCommentRecord> COMMUNITY_COMMENT_PKEY = Internal.createUniqueKey(CommunityComment.COMMUNITY_COMMENT, DSL.name("community_comment_pkey"), new TableField[] { CommunityComment.COMMUNITY_COMMENT.COMMENT_ID }, true);
    public static final UniqueKey<CommunityPostRecord> COMMUNITY_POST_PKEY = Internal.createUniqueKey(CommunityPost.COMMUNITY_POST, DSL.name("community_post_pkey"), new TableField[] { CommunityPost.COMMUNITY_POST.POST_ID }, true);
    public static final UniqueKey<CompanyRecord> COMPANY_PKEY = Internal.createUniqueKey(Company.COMPANY, DSL.name("company_pkey"), new TableField[] { Company.COMPANY.COMPANY_ID }, true);
    public static final UniqueKey<EmailGuestRecord> EMAIL_GUEST_PK = Internal.createUniqueKey(EmailGuest.EMAIL_GUEST, DSL.name("email_guest_pk"), new TableField[] { EmailGuest.EMAIL_GUEST.EMAIL_GUEST_ID }, true);
    public static final UniqueKey<EmailVerificationRecord> USER_EMAIL_VERIFICATION_PKEY = Internal.createUniqueKey(EmailVerification.EMAIL_VERIFICATION, DSL.name("user_email_verification_pkey"), new TableField[] { EmailVerification.EMAIL_VERIFICATION.EMAIL_VERIFICATION_ID }, true);
    public static final UniqueKey<EventRecord> EVENT_PKEY = Internal.createUniqueKey(Event.EVENT, DSL.name("event_pkey"), new TableField[] { Event.EVENT.EVENT_ID }, true);
    public static final UniqueKey<FileInfoRecord> FILE_INFO_PK = Internal.createUniqueKey(FileInfo.FILE_INFO, DSL.name("file_info_pk"), new TableField[] { FileInfo.FILE_INFO.FILE_ID }, true);
    public static final UniqueKey<GameScoreRecord> GAME_SCORE_PK = Internal.createUniqueKey(GameScore.GAME_SCORE, DSL.name("game_score_pk"), new TableField[] { GameScore.GAME_SCORE.SCORE_ID }, true);
    public static final UniqueKey<GameScoreRecord> GAME_SCORE_UNIQUE = Internal.createUniqueKey(GameScore.GAME_SCORE, DSL.name("game_score_unique"), new TableField[] { GameScore.GAME_SCORE.USER_ID, GameScore.GAME_SCORE.WEEK_START_DATE }, true);
    public static final UniqueKey<NoticeRecord> NOTICE_PK = Internal.createUniqueKey(Notice.NOTICE, DSL.name("notice_pk"), new TableField[] { Notice.NOTICE.NOTICE_ID }, true);
    public static final UniqueKey<OwnershipRecord> OWNERSHIP_PKEY = Internal.createUniqueKey(Ownership.OWNERSHIP, DSL.name("ownership_pkey"), new TableField[] { Ownership.OWNERSHIP.OWNERSHIP_ID }, true);
    public static final UniqueKey<PetRecord> PET_MICROCHIP_ID_KEY = Internal.createUniqueKey(Pet.PET, DSL.name("pet_microchip_id_key"), new TableField[] { Pet.PET.MICROCHIP_ID }, true);
    public static final UniqueKey<PetRecord> PET_PKEY = Internal.createUniqueKey(Pet.PET, DSL.name("pet_pkey"), new TableField[] { Pet.PET.PET_ID }, true);
    public static final UniqueKey<PetModeRecord> PET_MODE_PK = Internal.createUniqueKey(PetMode.PET_MODE, DSL.name("pet_mode_pk"), new TableField[] { PetMode.PET_MODE.PET_MODE_ID }, true);
    public static final UniqueKey<RoleRecord> USER_ROLE_PKEY = Internal.createUniqueKey(Role.ROLE, DSL.name("user_role_pkey"), new TableField[] { Role.ROLE.ROLE_ID }, true);
    public static final UniqueKey<SpeciesRecord> SPECIES_PKEY = Internal.createUniqueKey(Species.SPECIES, DSL.name("species_pkey"), new TableField[] { Species.SPECIES.SPECIES_ID }, true);
    public static final UniqueKey<UserRecord> USER_PKEY = Internal.createUniqueKey(User.USER, DSL.name("user_pkey"), new TableField[] { User.USER.USER_ID }, true);
    public static final UniqueKey<UserVoteCountRecord> USER_VOTE_COUNT_PK = Internal.createUniqueKey(UserVoteCount.USER_VOTE_COUNT, DSL.name("user_vote_count_pk"), new TableField[] { UserVoteCount.USER_VOTE_COUNT.USER_ID }, true);
    public static final UniqueKey<UserVoteCountHistoryRecord> USER_VOTE_COUNT_HISTORY_PK = Internal.createUniqueKey(UserVoteCountHistory.USER_VOTE_COUNT_HISTORY, DSL.name("user_vote_count_history_pk"), new TableField[] { UserVoteCountHistory.USER_VOTE_COUNT_HISTORY.HISTORY_ID }, true);
    public static final UniqueKey<VoteFileInfoRecord> VOTE_FILE_INFO_PKEY = Internal.createUniqueKey(VoteFileInfo.VOTE_FILE_INFO, DSL.name("vote_file_info_pkey"), new TableField[] { VoteFileInfo.VOTE_FILE_INFO.VOTE_FILE_ID }, true);
    public static final UniqueKey<VoteHistoryRecord> VOTE_HISTORY_PK = Internal.createUniqueKey(VoteHistory.VOTE_HISTORY, DSL.name("vote_history_pk"), new TableField[] { VoteHistory.VOTE_HISTORY.VOTE_HISTORY_ID }, true);
    public static final UniqueKey<VoteHistoryRecord> VOTE_HISTORY_UNIQUE = Internal.createUniqueKey(VoteHistory.VOTE_HISTORY, DSL.name("vote_history_unique"), new TableField[] { VoteHistory.VOTE_HISTORY.HISTORY_DATE, VoteHistory.VOTE_HISTORY.USER_ID, VoteHistory.VOTE_HISTORY.VOTE_ID, VoteHistory.VOTE_HISTORY.VOTE_CYCLE }, true);
    public static final UniqueKey<VoteHistoryRecord> VOTE_HISTORY_UNIQUE_1 = Internal.createUniqueKey(VoteHistory.VOTE_HISTORY, DSL.name("vote_history_unique_1"), new TableField[] { VoteHistory.VOTE_HISTORY.HISTORY_DATE, VoteHistory.VOTE_HISTORY.EMAIL, VoteHistory.VOTE_HISTORY.VOTE_ID, VoteHistory.VOTE_HISTORY.VOTE_CYCLE }, true);
    public static final UniqueKey<VoteWeeklyRecord> WEEKLY_VOTE_PKEY = Internal.createUniqueKey(VoteWeekly.VOTE_WEEKLY, DSL.name("weekly_vote_pkey"), new TableField[] { VoteWeekly.VOTE_WEEKLY.VOTE_WEEKLY_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BreedRecord, SpeciesRecord> BREED__BREED_SPECIES_ID_FKEY = Internal.createForeignKey(Breed.BREED, DSL.name("breed_species_id_fkey"), new TableField[] { Breed.BREED.SPECIES_ID }, Keys.SPECIES_PKEY, new TableField[] { Species.SPECIES.SPECIES_ID }, true);
    public static final ForeignKey<EmailVerificationRecord, UserRecord> EMAIL_VERIFICATION__FK_USER = Internal.createForeignKey(EmailVerification.EMAIL_VERIFICATION, DSL.name("fk_user"), new TableField[] { EmailVerification.EMAIL_VERIFICATION.USER_ID }, Keys.USER_PKEY, new TableField[] { User.USER.USER_ID }, true);
    public static final ForeignKey<PetRecord, BreedRecord> PET__PET_BREED_ID_FKEY = Internal.createForeignKey(Pet.PET, DSL.name("pet_breed_id_fkey"), new TableField[] { Pet.PET.BREED_ID }, Keys.BREED_PKEY, new TableField[] { Breed.BREED.BREED_ID }, true);
    public static final ForeignKey<PetRecord, OwnershipRecord> PET__PET_OWNERSHIP_ID_FKEY = Internal.createForeignKey(Pet.PET, DSL.name("pet_ownership_id_fkey"), new TableField[] { Pet.PET.OWNERSHIP_ID }, Keys.OWNERSHIP_PKEY, new TableField[] { Ownership.OWNERSHIP.OWNERSHIP_ID }, true);
    public static final ForeignKey<PetRecord, UserRecord> PET__PET_USER_ID_FKEY = Internal.createForeignKey(Pet.PET, DSL.name("pet_user_id_fkey"), new TableField[] { Pet.PET.USER_ID }, Keys.USER_PKEY, new TableField[] { User.USER.USER_ID }, true);
    public static final ForeignKey<UserRecord, CompanyRecord> USER__USER_COMPANY_ID_FKEY = Internal.createForeignKey(User.USER, DSL.name("user_company_id_fkey"), new TableField[] { User.USER.COMPANY_ID }, Keys.COMPANY_PKEY, new TableField[] { Company.COMPANY.COMPANY_ID }, true);
    public static final ForeignKey<UserRecord, RoleRecord> USER__USER_ROLE_ID_FKEY = Internal.createForeignKey(User.USER, DSL.name("user_role_id_fkey"), new TableField[] { User.USER.ROLE_ID }, Keys.USER_ROLE_PKEY, new TableField[] { Role.ROLE.ROLE_ID }, true);
    public static final ForeignKey<UserVoteCountRecord, UserRecord> USER_VOTE_COUNT__USER_VOTE_COUNT_USER_FK = Internal.createForeignKey(UserVoteCount.USER_VOTE_COUNT, DSL.name("user_vote_count_user_fk"), new TableField[] { UserVoteCount.USER_VOTE_COUNT.USER_ID }, Keys.USER_PKEY, new TableField[] { User.USER.USER_ID }, true);
    public static final ForeignKey<UserVoteCountHistoryRecord, UserRecord> USER_VOTE_COUNT_HISTORY__USER_VOTE_COUNT_HISTORY_USER_FK = Internal.createForeignKey(UserVoteCountHistory.USER_VOTE_COUNT_HISTORY, DSL.name("user_vote_count_history_user_fk"), new TableField[] { UserVoteCountHistory.USER_VOTE_COUNT_HISTORY.USER_ID }, Keys.USER_PKEY, new TableField[] { User.USER.USER_ID }, true);
}
