/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq;


import java.util.Arrays;
import java.util.List;

import kr.co.common.jooq.tables.Breed;
import kr.co.common.jooq.tables.CommunityComment;
import kr.co.common.jooq.tables.CommunityPost;
import kr.co.common.jooq.tables.Company;
import kr.co.common.jooq.tables.EmailGuest;
import kr.co.common.jooq.tables.EmailVerification;
import kr.co.common.jooq.tables.Event;
import kr.co.common.jooq.tables.FileInfo;
import kr.co.common.jooq.tables.GameScore;
import kr.co.common.jooq.tables.Notice;
import kr.co.common.jooq.tables.Ownership;
import kr.co.common.jooq.tables.Pet;
import kr.co.common.jooq.tables.PetMode;
import kr.co.common.jooq.tables.Role;
import kr.co.common.jooq.tables.Species;
import kr.co.common.jooq.tables.User;
import kr.co.common.jooq.tables.UserVoteCount;
import kr.co.common.jooq.tables.UserVoteCountHistory;
import kr.co.common.jooq.tables.VoteFileInfo;
import kr.co.common.jooq.tables.VoteHistory;
import kr.co.common.jooq.tables.VoteWeekly;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.breed</code>.
     */
    public final Breed BREED = Breed.BREED;

    /**
     * The table <code>public.community_comment</code>.
     */
    public final CommunityComment COMMUNITY_COMMENT = CommunityComment.COMMUNITY_COMMENT;

    /**
     * The table <code>public.community_post</code>.
     */
    public final CommunityPost COMMUNITY_POST = CommunityPost.COMMUNITY_POST;

    /**
     * The table <code>public.company</code>.
     */
    public final Company COMPANY = Company.COMPANY;

    /**
     * The table <code>public.email_guest</code>.
     */
    public final EmailGuest EMAIL_GUEST = EmailGuest.EMAIL_GUEST;

    /**
     * The table <code>public.email_verification</code>.
     */
    public final EmailVerification EMAIL_VERIFICATION = EmailVerification.EMAIL_VERIFICATION;

    /**
     * The table <code>public.event</code>.
     */
    public final Event EVENT = Event.EVENT;

    /**
     * The table <code>public.file_info</code>.
     */
    public final FileInfo FILE_INFO = FileInfo.FILE_INFO;

    /**
     * The table <code>public.game_score</code>.
     */
    public final GameScore GAME_SCORE = GameScore.GAME_SCORE;

    /**
     * The table <code>public.notice</code>.
     */
    public final Notice NOTICE = Notice.NOTICE;

    /**
     * The table <code>public.ownership</code>.
     */
    public final Ownership OWNERSHIP = Ownership.OWNERSHIP;

    /**
     * The table <code>public.pet</code>.
     */
    public final Pet PET = Pet.PET;

    /**
     * The table <code>public.pet_mode</code>.
     */
    public final PetMode PET_MODE = PetMode.PET_MODE;

    /**
     * The table <code>public.role</code>.
     */
    public final Role ROLE = Role.ROLE;

    /**
     * The table <code>public.species</code>.
     */
    public final Species SPECIES = Species.SPECIES;

    /**
     * The table <code>public.user</code>.
     */
    public final User USER = User.USER;

    /**
     * The table <code>public.user_vote_count</code>.
     */
    public final UserVoteCount USER_VOTE_COUNT = UserVoteCount.USER_VOTE_COUNT;

    /**
     * The table <code>public.user_vote_count_history</code>.
     */
    public final UserVoteCountHistory USER_VOTE_COUNT_HISTORY = UserVoteCountHistory.USER_VOTE_COUNT_HISTORY;

    /**
     * The table <code>public.vote_file_info</code>.
     */
    public final VoteFileInfo VOTE_FILE_INFO = VoteFileInfo.VOTE_FILE_INFO;

    /**
     * The table <code>public.vote_history</code>.
     */
    public final VoteHistory VOTE_HISTORY = VoteHistory.VOTE_HISTORY;

    /**
     * The table <code>public.vote_weekly</code>.
     */
    public final VoteWeekly VOTE_WEEKLY = VoteWeekly.VOTE_WEEKLY;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.USER_EMAIL_VERIFICATION_EMAIL_VERIFICATION_ID_SEQ
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Breed.BREED,
            CommunityComment.COMMUNITY_COMMENT,
            CommunityPost.COMMUNITY_POST,
            Company.COMPANY,
            EmailGuest.EMAIL_GUEST,
            EmailVerification.EMAIL_VERIFICATION,
            Event.EVENT,
            FileInfo.FILE_INFO,
            GameScore.GAME_SCORE,
            Notice.NOTICE,
            Ownership.OWNERSHIP,
            Pet.PET,
            PetMode.PET_MODE,
            Role.ROLE,
            Species.SPECIES,
            User.USER,
            UserVoteCount.USER_VOTE_COUNT,
            UserVoteCountHistory.USER_VOTE_COUNT_HISTORY,
            VoteFileInfo.VOTE_FILE_INFO,
            VoteHistory.VOTE_HISTORY,
            VoteWeekly.VOTE_WEEKLY
        );
    }
}
