/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sequences {

    /**
     * The sequence
     * <code>public.user_email_verification_email_verification_id_seq</code>
     */
    public static final Sequence<Long> USER_EMAIL_VERIFICATION_EMAIL_VERIFICATION_ID_SEQ = Internal.createSequence("user_email_verification_email_verification_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
