/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq;


import kr.co.common.jooq.tables.Breed;
import kr.co.common.jooq.tables.CommunityComment;
import kr.co.common.jooq.tables.CommunityPost;
import kr.co.common.jooq.tables.Company;
import kr.co.common.jooq.tables.EmailGuest;
import kr.co.common.jooq.tables.EmailVerification;
import kr.co.common.jooq.tables.Event;
import kr.co.common.jooq.tables.FileInfo;
import kr.co.common.jooq.tables.GameScore;
import kr.co.common.jooq.tables.Notice;
import kr.co.common.jooq.tables.Ownership;
import kr.co.common.jooq.tables.Pet;
import kr.co.common.jooq.tables.PetMode;
import kr.co.common.jooq.tables.Role;
import kr.co.common.jooq.tables.Species;
import kr.co.common.jooq.tables.User;
import kr.co.common.jooq.tables.VoteFileInfo;
import kr.co.common.jooq.tables.VoteHistory;
import kr.co.common.jooq.tables.VoteWeekly;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.breed</code>.
     */
    public static final Breed BREED = Breed.BREED;

    /**
     * The table <code>public.community_comment</code>.
     */
    public static final CommunityComment COMMUNITY_COMMENT = CommunityComment.COMMUNITY_COMMENT;

    /**
     * The table <code>public.community_post</code>.
     */
    public static final CommunityPost COMMUNITY_POST = CommunityPost.COMMUNITY_POST;

    /**
     * The table <code>public.company</code>.
     */
    public static final Company COMPANY = Company.COMPANY;

    /**
     * The table <code>public.email_guest</code>.
     */
    public static final EmailGuest EMAIL_GUEST = EmailGuest.EMAIL_GUEST;

    /**
     * The table <code>public.email_verification</code>.
     */
    public static final EmailVerification EMAIL_VERIFICATION = EmailVerification.EMAIL_VERIFICATION;

    /**
     * The table <code>public.event</code>.
     */
    public static final Event EVENT = Event.EVENT;

    /**
     * The table <code>public.file_info</code>.
     */
    public static final FileInfo FILE_INFO = FileInfo.FILE_INFO;

    /**
     * The table <code>public.game_score</code>.
     */
    public static final GameScore GAME_SCORE = GameScore.GAME_SCORE;

    /**
     * The table <code>public.notice</code>.
     */
    public static final Notice NOTICE = Notice.NOTICE;

    /**
     * The table <code>public.ownership</code>.
     */
    public static final Ownership OWNERSHIP = Ownership.OWNERSHIP;

    /**
     * The table <code>public.pet</code>.
     */
    public static final Pet PET = Pet.PET;

    /**
     * The table <code>public.pet_mode</code>.
     */
    public static final PetMode PET_MODE = PetMode.PET_MODE;

    /**
     * The table <code>public.role</code>.
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>public.species</code>.
     */
    public static final Species SPECIES = Species.SPECIES;

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>public.vote_file_info</code>.
     */
    public static final VoteFileInfo VOTE_FILE_INFO = VoteFileInfo.VOTE_FILE_INFO;

    /**
     * The table <code>public.vote_history</code>.
     */
    public static final VoteHistory VOTE_HISTORY = VoteHistory.VOTE_HISTORY;

    /**
     * The table <code>public.vote_weekly</code>.
     */
    public static final VoteWeekly VOTE_WEEKLY = VoteWeekly.VOTE_WEEKLY;
}
