/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.enums;


import kr.co.common.jooq.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum CommunityCategoryEnum implements EnumType {

    DAILY("DAILY"),

    QUESTION("QUESTION"),

    TIP("TIP");

    private final String literal;

    private CommunityCategoryEnum(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "community_category_enum";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static CommunityCategoryEnum lookupLiteral(String literal) {
        return EnumType.lookupLiteral(CommunityCategoryEnum.class, literal);
    }
}
