/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.enums;


import kr.co.common.jooq.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum RefTableEnum implements EnumType {

    notice("notice"),

    event("event"),

    community("community"),

    user("user"),

    pet("pet"),

    vote_weekly("vote_weekly"),

    vote_monthly("vote_monthly");

    private final String literal;

    private RefTableEnum(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "ref_table_enum";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static RefTableEnum lookupLiteral(String literal) {
        return EnumType.lookupLiteral(RefTableEnum.class, literal);
    }
}
