/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables.records;


import java.time.LocalDateTime;

import kr.co.common.jooq.tables.Breed;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BreedRecord extends UpdatableRecordImpl<BreedRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.breed.breed_id</code>.
     */
    public BreedRecord setBreedId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.breed.breed_id</code>.
     */
    public Integer getBreedId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.breed.species_id</code>.
     */
    public BreedRecord setSpeciesId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.breed.species_id</code>.
     */
    public Long getSpeciesId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.breed.name</code>.
     */
    public BreedRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.breed.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.breed.create_date</code>.
     */
    public BreedRecord setCreateDate(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.breed.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.breed.create_user_id</code>.
     */
    public BreedRecord setCreateUserId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.breed.create_user_id</code>.
     */
    public Long getCreateUserId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.breed.update_date</code>.
     */
    public BreedRecord setUpdateDate(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.breed.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.breed.update_user_id</code>.
     */
    public BreedRecord setUpdateUserId(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.breed.update_user_id</code>.
     */
    public Long getUpdateUserId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.breed.delete_date</code>.
     */
    public BreedRecord setDeleteDate(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.breed.delete_date</code>.
     */
    public LocalDateTime getDeleteDate() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.breed.delete_user_id</code>.
     */
    public BreedRecord setDeleteUserId(Long value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.breed.delete_user_id</code>.
     */
    public Long getDeleteUserId() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BreedRecord
     */
    public BreedRecord() {
        super(Breed.BREED);
    }

    /**
     * Create a detached, initialised BreedRecord
     */
    public BreedRecord(Integer breedId, Long speciesId, String name, LocalDateTime createDate, Long createUserId, LocalDateTime updateDate, Long updateUserId, LocalDateTime deleteDate, Long deleteUserId) {
        super(Breed.BREED);

        setBreedId(breedId);
        setSpeciesId(speciesId);
        setName(name);
        setCreateDate(createDate);
        setCreateUserId(createUserId);
        setUpdateDate(updateDate);
        setUpdateUserId(updateUserId);
        setDeleteDate(deleteDate);
        setDeleteUserId(deleteUserId);
        resetChangedOnNotNull();
    }
}
