/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables.records;


import java.time.LocalDateTime;

import kr.co.common.jooq.enums.CommunityCategoryEnum;
import kr.co.common.jooq.tables.CommunityPost;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CommunityPostRecord extends UpdatableRecordImpl<CommunityPostRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.community_post.post_id</code>.
     */
    public CommunityPostRecord setPostId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.community_post.post_id</code>.
     */
    public Long getPostId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.community_post.create_date</code>.
     */
    public CommunityPostRecord setCreateDate(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.community_post.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.community_post.create_user_id</code>.
     */
    public CommunityPostRecord setCreateUserId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.community_post.create_user_id</code>.
     */
    public Long getCreateUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.community_post.update_date</code>.
     */
    public CommunityPostRecord setUpdateDate(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.community_post.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.community_post.update_user_id</code>.
     */
    public CommunityPostRecord setUpdateUserId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.community_post.update_user_id</code>.
     */
    public Long getUpdateUserId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.community_post.delete_date</code>.
     */
    public CommunityPostRecord setDeleteDate(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.community_post.delete_date</code>.
     */
    public LocalDateTime getDeleteDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.community_post.delete_user_id</code>.
     */
    public CommunityPostRecord setDeleteUserId(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.community_post.delete_user_id</code>.
     */
    public Long getDeleteUserId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.community_post.user_id</code>.
     */
    public CommunityPostRecord setUserId(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.community_post.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.community_post.title</code>.
     */
    public CommunityPostRecord setTitle(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.community_post.title</code>.
     */
    public String getTitle() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.community_post.content</code>.
     */
    public CommunityPostRecord setContent(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.community_post.content</code>.
     */
    public String getContent() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.community_post.content_type</code>.
     */
    public CommunityPostRecord setContentType(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.community_post.content_type</code>.
     */
    public String getContentType() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.community_post.view_count</code>.
     */
    public CommunityPostRecord setViewCount(Long value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.community_post.view_count</code>.
     */
    public Long getViewCount() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>public.community_post.like_count</code>.
     */
    public CommunityPostRecord setLikeCount(Long value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.community_post.like_count</code>.
     */
    public Long getLikeCount() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>public.community_post.comment_count</code>.
     */
    public CommunityPostRecord setCommentCount(Long value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.community_post.comment_count</code>.
     */
    public Long getCommentCount() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>public.community_post.is_pinned</code>.
     */
    public CommunityPostRecord setIsPinned(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.community_post.is_pinned</code>.
     */
    public String getIsPinned() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.community_post.pin_order</code>.
     */
    public CommunityPostRecord setPinOrder(Integer value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>public.community_post.pin_order</code>.
     */
    public Integer getPinOrder() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>public.community_post.category</code>.
     */
    public CommunityPostRecord setCategory(CommunityCategoryEnum value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>public.community_post.category</code>.
     */
    public CommunityCategoryEnum getCategory() {
        return (CommunityCategoryEnum) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CommunityPostRecord
     */
    public CommunityPostRecord() {
        super(CommunityPost.COMMUNITY_POST);
    }

    /**
     * Create a detached, initialised CommunityPostRecord
     */
    public CommunityPostRecord(Long postId, LocalDateTime createDate, Long createUserId, LocalDateTime updateDate, Long updateUserId, LocalDateTime deleteDate, Long deleteUserId, Long userId, String title, String content, String contentType, Long viewCount, Long likeCount, Long commentCount, String isPinned, Integer pinOrder, CommunityCategoryEnum category) {
        super(CommunityPost.COMMUNITY_POST);

        setPostId(postId);
        setCreateDate(createDate);
        setCreateUserId(createUserId);
        setUpdateDate(updateDate);
        setUpdateUserId(updateUserId);
        setDeleteDate(deleteDate);
        setDeleteUserId(deleteUserId);
        setUserId(userId);
        setTitle(title);
        setContent(content);
        setContentType(contentType);
        setViewCount(viewCount);
        setLikeCount(likeCount);
        setCommentCount(commentCount);
        setIsPinned(isPinned);
        setPinOrder(pinOrder);
        setCategory(category);
        resetChangedOnNotNull();
    }
}
