/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables.records;


import java.time.LocalDateTime;

import kr.co.common.jooq.tables.CommunityComment;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CommunityCommentRecord extends UpdatableRecordImpl<CommunityCommentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.community_comment.comment_id</code>.
     */
    public CommunityCommentRecord setCommentId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.community_comment.comment_id</code>.
     */
    public Long getCommentId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.community_comment.create_date</code>.
     */
    public CommunityCommentRecord setCreateDate(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.community_comment.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.community_comment.create_user_id</code>.
     */
    public CommunityCommentRecord setCreateUserId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.community_comment.create_user_id</code>.
     */
    public Long getCreateUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.community_comment.update_date</code>.
     */
    public CommunityCommentRecord setUpdateDate(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.community_comment.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.community_comment.update_user_id</code>.
     */
    public CommunityCommentRecord setUpdateUserId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.community_comment.update_user_id</code>.
     */
    public Long getUpdateUserId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.community_comment.delete_date</code>.
     */
    public CommunityCommentRecord setDeleteDate(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.community_comment.delete_date</code>.
     */
    public LocalDateTime getDeleteDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.community_comment.delete_user_id</code>.
     */
    public CommunityCommentRecord setDeleteUserId(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.community_comment.delete_user_id</code>.
     */
    public Long getDeleteUserId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.community_comment.post_id</code>.
     */
    public CommunityCommentRecord setPostId(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.community_comment.post_id</code>.
     */
    public Long getPostId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.community_comment.user_id</code>.
     */
    public CommunityCommentRecord setUserId(Long value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.community_comment.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.community_comment.content</code>.
     */
    public CommunityCommentRecord setContent(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.community_comment.content</code>.
     */
    public String getContent() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.community_comment.like_count</code>.
     */
    public CommunityCommentRecord setLikeCount(Long value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.community_comment.like_count</code>.
     */
    public Long getLikeCount() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>public.community_comment.parent_comment_id</code>.
     */
    public CommunityCommentRecord setParentCommentId(Long value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.community_comment.parent_comment_id</code>.
     */
    public Long getParentCommentId() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>public.community_comment.depth</code>.
     */
    public CommunityCommentRecord setDepth(Integer value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.community_comment.depth</code>.
     */
    public Integer getDepth() {
        return (Integer) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CommunityCommentRecord
     */
    public CommunityCommentRecord() {
        super(CommunityComment.COMMUNITY_COMMENT);
    }

    /**
     * Create a detached, initialised CommunityCommentRecord
     */
    public CommunityCommentRecord(Long commentId, LocalDateTime createDate, Long createUserId, LocalDateTime updateDate, Long updateUserId, LocalDateTime deleteDate, Long deleteUserId, Long postId, Long userId, String content, Long likeCount, Long parentCommentId, Integer depth) {
        super(CommunityComment.COMMUNITY_COMMENT);

        setCommentId(commentId);
        setCreateDate(createDate);
        setCreateUserId(createUserId);
        setUpdateDate(updateDate);
        setUpdateUserId(updateUserId);
        setDeleteDate(deleteDate);
        setDeleteUserId(deleteUserId);
        setPostId(postId);
        setUserId(userId);
        setContent(content);
        setLikeCount(likeCount);
        setParentCommentId(parentCommentId);
        setDepth(depth);
        resetChangedOnNotNull();
    }
}
