/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables.records;


import java.time.LocalDateTime;

import kr.co.common.jooq.tables.Company;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CompanyRecord extends UpdatableRecordImpl<CompanyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.company.company_id</code>.
     */
    public CompanyRecord setCompanyId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.company.company_id</code>.
     */
    public Integer getCompanyId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.company.company_name</code>.
     */
    public CompanyRecord setCompanyName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.company.company_name</code>.
     */
    public String getCompanyName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.company.company_code</code>.
     */
    public CompanyRecord setCompanyCode(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.company.company_code</code>.
     */
    public String getCompanyCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.company.address</code>.
     */
    public CompanyRecord setAddress(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.company.address</code>.
     */
    public String getAddress() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.company.phone_number</code>.
     */
    public CompanyRecord setPhoneNumber(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.company.phone_number</code>.
     */
    public String getPhoneNumber() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.company.create_date</code>.
     */
    public CompanyRecord setCreateDate(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.company.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.company.create_user_id</code>.
     */
    public CompanyRecord setCreateUserId(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.company.create_user_id</code>.
     */
    public Long getCreateUserId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.company.update_date</code>.
     */
    public CompanyRecord setUpdateDate(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.company.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.company.update_user_id</code>.
     */
    public CompanyRecord setUpdateUserId(Long value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.company.update_user_id</code>.
     */
    public Long getUpdateUserId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.company.delete_date</code>.
     */
    public CompanyRecord setDeleteDate(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.company.delete_date</code>.
     */
    public LocalDateTime getDeleteDate() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>public.company.is_default</code>.
     */
    public CompanyRecord setIsDefault(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.company.is_default</code>.
     */
    public String getIsDefault() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.company.delete_user_id</code>.
     */
    public CompanyRecord setDeleteUserId(Long value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.company.delete_user_id</code>.
     */
    public Long getDeleteUserId() {
        return (Long) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CompanyRecord
     */
    public CompanyRecord() {
        super(Company.COMPANY);
    }

    /**
     * Create a detached, initialised CompanyRecord
     */
    public CompanyRecord(Integer companyId, String companyName, String companyCode, String address, String phoneNumber, LocalDateTime createDate, Long createUserId, LocalDateTime updateDate, Long updateUserId, LocalDateTime deleteDate, String isDefault, Long deleteUserId) {
        super(Company.COMPANY);

        setCompanyId(companyId);
        setCompanyName(companyName);
        setCompanyCode(companyCode);
        setAddress(address);
        setPhoneNumber(phoneNumber);
        setCreateDate(createDate);
        setCreateUserId(createUserId);
        setUpdateDate(updateDate);
        setUpdateUserId(updateUserId);
        setDeleteDate(deleteDate);
        setIsDefault(isDefault);
        setDeleteUserId(deleteUserId);
        resetChangedOnNotNull();
    }
}
