/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables.records;


import java.time.LocalDate;
import java.time.LocalDateTime;

import kr.co.common.jooq.tables.EmailGuest;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EmailGuestRecord extends UpdatableRecordImpl<EmailGuestRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.email_guest.email_guest_id</code>.
     */
    public EmailGuestRecord setEmailGuestId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.email_guest.email_guest_id</code>.
     */
    public Long getEmailGuestId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.email_guest.create_date</code>.
     */
    public EmailGuestRecord setCreateDate(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.email_guest.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.email_guest.email</code>.
     */
    public EmailGuestRecord setEmail(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.email_guest.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.email_guest.join_date</code>.
     */
    public EmailGuestRecord setJoinDate(LocalDate value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.email_guest.join_date</code>.
     */
    public LocalDate getJoinDate() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>public.email_guest.encrypte_token</code>.
     */
    public EmailGuestRecord setEncrypteToken(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.email_guest.encrypte_token</code>.
     */
    public String getEncrypteToken() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmailGuestRecord
     */
    public EmailGuestRecord() {
        super(EmailGuest.EMAIL_GUEST);
    }

    /**
     * Create a detached, initialised EmailGuestRecord
     */
    public EmailGuestRecord(Long emailGuestId, LocalDateTime createDate, String email, LocalDate joinDate, String encrypteToken) {
        super(EmailGuest.EMAIL_GUEST);

        setEmailGuestId(emailGuestId);
        setCreateDate(createDate);
        setEmail(email);
        setJoinDate(joinDate);
        setEncrypteToken(encrypteToken);
        resetChangedOnNotNull();
    }
}
