/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables.records;


import java.time.LocalDateTime;

import kr.co.common.jooq.tables.EmailVerification;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EmailVerificationRecord extends UpdatableRecordImpl<EmailVerificationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.email_verification.email_verification_id</code>.
     */
    public EmailVerificationRecord setEmailVerificationId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.email_verification.email_verification_id</code>.
     */
    public Long getEmailVerificationId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.email_verification.user_id</code>.
     */
    public EmailVerificationRecord setUserId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.email_verification.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.email_verification.verification_code</code>.
     */
    public EmailVerificationRecord setVerificationCode(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.email_verification.verification_code</code>.
     */
    public String getVerificationCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.email_verification.expires_date</code>.
     */
    public EmailVerificationRecord setExpiresDate(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.email_verification.expires_date</code>.
     */
    public LocalDateTime getExpiresDate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.email_verification.create_date</code>.
     */
    public EmailVerificationRecord setCreateDate(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.email_verification.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.email_verification.create_user_id</code>.
     */
    public EmailVerificationRecord setCreateUserId(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.email_verification.create_user_id</code>.
     */
    public Long getCreateUserId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.email_verification.update_date</code>.
     */
    public EmailVerificationRecord setUpdateDate(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.email_verification.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.email_verification.update_user_id</code>.
     */
    public EmailVerificationRecord setUpdateUserId(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.email_verification.update_user_id</code>.
     */
    public Long getUpdateUserId() {
        return (Long) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmailVerificationRecord
     */
    public EmailVerificationRecord() {
        super(EmailVerification.EMAIL_VERIFICATION);
    }

    /**
     * Create a detached, initialised EmailVerificationRecord
     */
    public EmailVerificationRecord(Long emailVerificationId, Long userId, String verificationCode, LocalDateTime expiresDate, LocalDateTime createDate, Long createUserId, LocalDateTime updateDate, Long updateUserId) {
        super(EmailVerification.EMAIL_VERIFICATION);

        setEmailVerificationId(emailVerificationId);
        setUserId(userId);
        setVerificationCode(verificationCode);
        setExpiresDate(expiresDate);
        setCreateDate(createDate);
        setCreateUserId(createUserId);
        setUpdateDate(updateDate);
        setUpdateUserId(updateUserId);
        resetChangedOnNotNull();
    }
}
