/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables.records;


import java.time.LocalDateTime;

import kr.co.common.jooq.enums.FileTypeEnum;
import kr.co.common.jooq.enums.RefTableEnum;
import kr.co.common.jooq.tables.FileInfo;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FileInfoRecord extends UpdatableRecordImpl<FileInfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.file_info.file_id</code>.
     */
    public FileInfoRecord setFileId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.file_info.file_id</code>.
     */
    public Long getFileId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.file_info.create_date</code>.
     */
    public FileInfoRecord setCreateDate(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.file_info.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.file_info.create_user_id</code>.
     */
    public FileInfoRecord setCreateUserId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.file_info.create_user_id</code>.
     */
    public Long getCreateUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.file_info.updated_date</code>.
     */
    public FileInfoRecord setUpdatedDate(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.file_info.updated_date</code>.
     */
    public LocalDateTime getUpdatedDate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.file_info.update_user_id</code>.
     */
    public FileInfoRecord setUpdateUserId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.file_info.update_user_id</code>.
     */
    public Long getUpdateUserId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.file_info.delete_date</code>.
     */
    public FileInfoRecord setDeleteDate(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.file_info.delete_date</code>.
     */
    public LocalDateTime getDeleteDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.file_info.delete_user_id</code>.
     */
    public FileInfoRecord setDeleteUserId(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.file_info.delete_user_id</code>.
     */
    public Long getDeleteUserId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.file_info.ref_table</code>.
     */
    public FileInfoRecord setRefTable(RefTableEnum value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.file_info.ref_table</code>.
     */
    public RefTableEnum getRefTable() {
        return (RefTableEnum) get(7);
    }

    /**
     * Setter for <code>public.file_info.ref_id</code>.
     */
    public FileInfoRecord setRefId(Long value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.file_info.ref_id</code>.
     */
    public Long getRefId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.file_info.file_type</code>.
     */
    public FileInfoRecord setFileType(FileTypeEnum value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.file_info.file_type</code>.
     */
    public FileTypeEnum getFileType() {
        return (FileTypeEnum) get(9);
    }

    /**
     * Setter for <code>public.file_info.sort_order</code>.
     */
    public FileInfoRecord setSortOrder(Integer value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.file_info.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.file_info.file_url</code>.
     */
    public FileInfoRecord setFileUrl(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.file_info.file_url</code>.
     */
    public String getFileUrl() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.file_info.file_size</code>.
     */
    public FileInfoRecord setFileSize(Long value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.file_info.file_size</code>.
     */
    public Long getFileSize() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>public.file_info.mime_type</code>.
     */
    public FileInfoRecord setMimeType(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.file_info.mime_type</code>.
     */
    public String getMimeType() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.file_info.file_name</code>.
     */
    public FileInfoRecord setFileName(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.file_info.file_name</code>.
     */
    public String getFileName() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.file_info.original_file_name</code>.
     */
    public FileInfoRecord setOriginalFileName(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>public.file_info.original_file_name</code>.
     */
    public String getOriginalFileName() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FileInfoRecord
     */
    public FileInfoRecord() {
        super(FileInfo.FILE_INFO);
    }

    /**
     * Create a detached, initialised FileInfoRecord
     */
    public FileInfoRecord(Long fileId, LocalDateTime createDate, Long createUserId, LocalDateTime updatedDate, Long updateUserId, LocalDateTime deleteDate, Long deleteUserId, RefTableEnum refTable, Long refId, FileTypeEnum fileType, Integer sortOrder, String fileUrl, Long fileSize, String mimeType, String fileName, String originalFileName) {
        super(FileInfo.FILE_INFO);

        setFileId(fileId);
        setCreateDate(createDate);
        setCreateUserId(createUserId);
        setUpdatedDate(updatedDate);
        setUpdateUserId(updateUserId);
        setDeleteDate(deleteDate);
        setDeleteUserId(deleteUserId);
        setRefTable(refTable);
        setRefId(refId);
        setFileType(fileType);
        setSortOrder(sortOrder);
        setFileUrl(fileUrl);
        setFileSize(fileSize);
        setMimeType(mimeType);
        setFileName(fileName);
        setOriginalFileName(originalFileName);
        resetChangedOnNotNull();
    }
}
