/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables.records;


import java.time.LocalDate;
import java.time.LocalDateTime;

import kr.co.common.jooq.tables.GameScore;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GameScoreRecord extends UpdatableRecordImpl<GameScoreRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.game_score.score_id</code>.
     */
    public GameScoreRecord setScoreId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.game_score.score_id</code>.
     */
    public Long getScoreId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.game_score.create_date</code>.
     */
    public GameScoreRecord setCreateDate(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.game_score.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.game_score.create_user_id</code>.
     */
    public GameScoreRecord setCreateUserId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.game_score.create_user_id</code>.
     */
    public Long getCreateUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.game_score.update_date</code>.
     */
    public GameScoreRecord setUpdateDate(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.game_score.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.game_score.update_user_id</code>.
     */
    public GameScoreRecord setUpdateUserId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.game_score.update_user_id</code>.
     */
    public Long getUpdateUserId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.game_score.user_id</code>.
     */
    public GameScoreRecord setUserId(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.game_score.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.game_score.week_start_date</code>.
     */
    public GameScoreRecord setWeekStartDate(LocalDate value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.game_score.week_start_date</code>.
     */
    public LocalDate getWeekStartDate() {
        return (LocalDate) get(6);
    }

    /**
     * Setter for <code>public.game_score.score</code>.
     */
    public GameScoreRecord setScore(Double value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.game_score.score</code>.
     */
    public Double getScore() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>public.game_score.pet_id</code>.
     */
    public GameScoreRecord setPetId(Long value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.game_score.pet_id</code>.
     */
    public Long getPetId() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameScoreRecord
     */
    public GameScoreRecord() {
        super(GameScore.GAME_SCORE);
    }

    /**
     * Create a detached, initialised GameScoreRecord
     */
    public GameScoreRecord(Long scoreId, LocalDateTime createDate, Long createUserId, LocalDateTime updateDate, Long updateUserId, Long userId, LocalDate weekStartDate, Double score, Long petId) {
        super(GameScore.GAME_SCORE);

        setScoreId(scoreId);
        setCreateDate(createDate);
        setCreateUserId(createUserId);
        setUpdateDate(updateDate);
        setUpdateUserId(updateUserId);
        setUserId(userId);
        setWeekStartDate(weekStartDate);
        setScore(score);
        setPetId(petId);
        resetChangedOnNotNull();
    }
}
