/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables.records;


import java.time.LocalDateTime;

import kr.co.common.jooq.tables.Notice;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NoticeRecord extends UpdatableRecordImpl<NoticeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.notice.notice_id</code>.
     */
    public NoticeRecord setNoticeId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.notice.notice_id</code>.
     */
    public Long getNoticeId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.notice.create_date</code>.
     */
    public NoticeRecord setCreateDate(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.notice.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.notice.create_user_id</code>.
     */
    public NoticeRecord setCreateUserId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.notice.create_user_id</code>.
     */
    public Long getCreateUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.notice.updated_date</code>.
     */
    public NoticeRecord setUpdatedDate(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.notice.updated_date</code>.
     */
    public LocalDateTime getUpdatedDate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.notice.update_user_id</code>.
     */
    public NoticeRecord setUpdateUserId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.notice.update_user_id</code>.
     */
    public Long getUpdateUserId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.notice.delete_date</code>.
     */
    public NoticeRecord setDeleteDate(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.notice.delete_date</code>.
     */
    public LocalDateTime getDeleteDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.notice.delete_user_id</code>.
     */
    public NoticeRecord setDeleteUserId(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.notice.delete_user_id</code>.
     */
    public Long getDeleteUserId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.notice.title</code>.
     */
    public NoticeRecord setTitle(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.notice.title</code>.
     */
    public String getTitle() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.notice.content</code>.
     */
    public NoticeRecord setContent(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.notice.content</code>.
     */
    public String getContent() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.notice.content_type</code>.
     */
    public NoticeRecord setContentType(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.notice.content_type</code>.
     */
    public String getContentType() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.notice.is_pinned</code>.
     */
    public NoticeRecord setIsPinned(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.notice.is_pinned</code>.
     */
    public String getIsPinned() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.notice.pin_order</code>.
     */
    public NoticeRecord setPinOrder(Integer value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.notice.pin_order</code>.
     */
    public Integer getPinOrder() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.notice.start_date</code>.
     */
    public NoticeRecord setStartDate(LocalDateTime value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.notice.start_date</code>.
     */
    public LocalDateTime getStartDate() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>public.notice.end_date</code>.
     */
    public NoticeRecord setEndDate(LocalDateTime value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.notice.end_date</code>.
     */
    public LocalDateTime getEndDate() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>public.notice.view_count</code>.
     */
    public NoticeRecord setViewCount(Long value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.notice.view_count</code>.
     */
    public Long getViewCount() {
        return (Long) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NoticeRecord
     */
    public NoticeRecord() {
        super(Notice.NOTICE);
    }

    /**
     * Create a detached, initialised NoticeRecord
     */
    public NoticeRecord(Long noticeId, LocalDateTime createDate, Long createUserId, LocalDateTime updatedDate, Long updateUserId, LocalDateTime deleteDate, Long deleteUserId, String title, String content, String contentType, String isPinned, Integer pinOrder, LocalDateTime startDate, LocalDateTime endDate, Long viewCount) {
        super(Notice.NOTICE);

        setNoticeId(noticeId);
        setCreateDate(createDate);
        setCreateUserId(createUserId);
        setUpdatedDate(updatedDate);
        setUpdateUserId(updateUserId);
        setDeleteDate(deleteDate);
        setDeleteUserId(deleteUserId);
        setTitle(title);
        setContent(content);
        setContentType(contentType);
        setIsPinned(isPinned);
        setPinOrder(pinOrder);
        setStartDate(startDate);
        setEndDate(endDate);
        setViewCount(viewCount);
        resetChangedOnNotNull();
    }
}
