/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables.records;


import java.time.LocalDateTime;

import kr.co.common.jooq.tables.Ownership;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OwnershipRecord extends UpdatableRecordImpl<OwnershipRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.ownership.ownership_id</code>.
     */
    public OwnershipRecord setOwnershipId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.ownership.ownership_id</code>.
     */
    public Integer getOwnershipId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.ownership.ownership_name</code>.
     */
    public OwnershipRecord setOwnershipName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.ownership.ownership_name</code>.
     */
    public String getOwnershipName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.ownership.create_date</code>.
     */
    public OwnershipRecord setCreateDate(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.ownership.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.ownership.create_user_id</code>.
     */
    public OwnershipRecord setCreateUserId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.ownership.create_user_id</code>.
     */
    public Long getCreateUserId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.ownership.update_date</code>.
     */
    public OwnershipRecord setUpdateDate(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.ownership.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.ownership.update_user_id</code>.
     */
    public OwnershipRecord setUpdateUserId(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.ownership.update_user_id</code>.
     */
    public Long getUpdateUserId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.ownership.delete_date</code>.
     */
    public OwnershipRecord setDeleteDate(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.ownership.delete_date</code>.
     */
    public LocalDateTime getDeleteDate() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.ownership.delete_user_id</code>.
     */
    public OwnershipRecord setDeleteUserId(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.ownership.delete_user_id</code>.
     */
    public Long getDeleteUserId() {
        return (Long) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OwnershipRecord
     */
    public OwnershipRecord() {
        super(Ownership.OWNERSHIP);
    }

    /**
     * Create a detached, initialised OwnershipRecord
     */
    public OwnershipRecord(Integer ownershipId, String ownershipName, LocalDateTime createDate, Long createUserId, LocalDateTime updateDate, Long updateUserId, LocalDateTime deleteDate, Long deleteUserId) {
        super(Ownership.OWNERSHIP);

        setOwnershipId(ownershipId);
        setOwnershipName(ownershipName);
        setCreateDate(createDate);
        setCreateUserId(createUserId);
        setUpdateDate(updateDate);
        setUpdateUserId(updateUserId);
        setDeleteDate(deleteDate);
        setDeleteUserId(deleteUserId);
        resetChangedOnNotNull();
    }
}
