/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables.records;


import java.time.LocalDateTime;

import kr.co.common.jooq.tables.PetMode;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PetModeRecord extends UpdatableRecordImpl<PetModeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.pet_mode.pet_mode_id</code>.
     */
    public PetModeRecord setPetModeId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.pet_mode.pet_mode_id</code>.
     */
    public Integer getPetModeId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.pet_mode.create_date</code>.
     */
    public PetModeRecord setCreateDate(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.pet_mode.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.pet_mode.create_user_id</code>.
     */
    public PetModeRecord setCreateUserId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.pet_mode.create_user_id</code>.
     */
    public Long getCreateUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.pet_mode.update_date</code>.
     */
    public PetModeRecord setUpdateDate(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.pet_mode.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.pet_mode.update_user_id</code>.
     */
    public PetModeRecord setUpdateUserId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.pet_mode.update_user_id</code>.
     */
    public Long getUpdateUserId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.pet_mode.delete_date</code>.
     */
    public PetModeRecord setDeleteDate(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.pet_mode.delete_date</code>.
     */
    public LocalDateTime getDeleteDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.pet_mode.delete_user_id</code>.
     */
    public PetModeRecord setDeleteUserId(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.pet_mode.delete_user_id</code>.
     */
    public Long getDeleteUserId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.pet_mode.mode_name</code>.
     */
    public PetModeRecord setModeName(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.pet_mode.mode_name</code>.
     */
    public String getModeName() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PetModeRecord
     */
    public PetModeRecord() {
        super(PetMode.PET_MODE);
    }

    /**
     * Create a detached, initialised PetModeRecord
     */
    public PetModeRecord(Integer petModeId, LocalDateTime createDate, Long createUserId, LocalDateTime updateDate, Long updateUserId, LocalDateTime deleteDate, Long deleteUserId, String modeName) {
        super(PetMode.PET_MODE);

        setPetModeId(petModeId);
        setCreateDate(createDate);
        setCreateUserId(createUserId);
        setUpdateDate(updateDate);
        setUpdateUserId(updateUserId);
        setDeleteDate(deleteDate);
        setDeleteUserId(deleteUserId);
        setModeName(modeName);
        resetChangedOnNotNull();
    }
}
