/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables.records;


import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import kr.co.common.jooq.tables.Pet;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PetRecord extends UpdatableRecordImpl<PetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.pet.pet_id</code>.
     */
    public PetRecord setPetId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.pet.pet_id</code>.
     */
    public Long getPetId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.pet.breed_id</code>.
     */
    public PetRecord setBreedId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.pet.breed_id</code>.
     */
    public Long getBreedId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.pet.custom_breed</code>.
     */
    public PetRecord setCustomBreed(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.pet.custom_breed</code>.
     */
    public String getCustomBreed() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.pet.ownership_id</code>.
     */
    public PetRecord setOwnershipId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.pet.ownership_id</code>.
     */
    public Long getOwnershipId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.pet.user_id</code>.
     */
    public PetRecord setUserId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.pet.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.pet.name</code>.
     */
    public PetRecord setName(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.pet.name</code>.
     */
    public String getName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.pet.birth_date</code>.
     */
    public PetRecord setBirthDate(LocalDate value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.pet.birth_date</code>.
     */
    public LocalDate getBirthDate() {
        return (LocalDate) get(6);
    }

    /**
     * Setter for <code>public.pet.gender</code>.
     */
    public PetRecord setGender(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.pet.gender</code>.
     */
    public String getGender() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.pet.weight</code>.
     */
    public PetRecord setWeight(BigDecimal value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.pet.weight</code>.
     */
    public BigDecimal getWeight() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>public.pet.height</code>.
     */
    public PetRecord setHeight(BigDecimal value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.pet.height</code>.
     */
    public BigDecimal getHeight() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>public.pet.is_neutered</code>.
     */
    public PetRecord setIsNeutered(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.pet.is_neutered</code>.
     */
    public String getIsNeutered() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.pet.microchip_id</code>.
     */
    public PetRecord setMicrochipId(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.pet.microchip_id</code>.
     */
    public String getMicrochipId() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.pet.description</code>.
     */
    public PetRecord setDescription(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.pet.description</code>.
     */
    public String getDescription() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.pet.create_date</code>.
     */
    public PetRecord setCreateDate(LocalDateTime value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.pet.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>public.pet.create_user_id</code>.
     */
    public PetRecord setCreateUserId(Long value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.pet.create_user_id</code>.
     */
    public Long getCreateUserId() {
        return (Long) get(14);
    }

    /**
     * Setter for <code>public.pet.update_date</code>.
     */
    public PetRecord setUpdateDate(LocalDateTime value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>public.pet.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>public.pet.update_user_id</code>.
     */
    public PetRecord setUpdateUserId(Long value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>public.pet.update_user_id</code>.
     */
    public Long getUpdateUserId() {
        return (Long) get(16);
    }

    /**
     * Setter for <code>public.pet.delete_date</code>.
     */
    public PetRecord setDeleteDate(LocalDateTime value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>public.pet.delete_date</code>.
     */
    public LocalDateTime getDeleteDate() {
        return (LocalDateTime) get(17);
    }

    /**
     * Setter for <code>public.pet.delete_user_id</code>.
     */
    public PetRecord setDeleteUserId(Long value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>public.pet.delete_user_id</code>.
     */
    public Long getDeleteUserId() {
        return (Long) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PetRecord
     */
    public PetRecord() {
        super(Pet.PET);
    }

    /**
     * Create a detached, initialised PetRecord
     */
    public PetRecord(Long petId, Long breedId, String customBreed, Long ownershipId, Long userId, String name, LocalDate birthDate, String gender, BigDecimal weight, BigDecimal height, String isNeutered, String microchipId, String description, LocalDateTime createDate, Long createUserId, LocalDateTime updateDate, Long updateUserId, LocalDateTime deleteDate, Long deleteUserId) {
        super(Pet.PET);

        setPetId(petId);
        setBreedId(breedId);
        setCustomBreed(customBreed);
        setOwnershipId(ownershipId);
        setUserId(userId);
        setName(name);
        setBirthDate(birthDate);
        setGender(gender);
        setWeight(weight);
        setHeight(height);
        setIsNeutered(isNeutered);
        setMicrochipId(microchipId);
        setDescription(description);
        setCreateDate(createDate);
        setCreateUserId(createUserId);
        setUpdateDate(updateDate);
        setUpdateUserId(updateUserId);
        setDeleteDate(deleteDate);
        setDeleteUserId(deleteUserId);
        resetChangedOnNotNull();
    }
}
