/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables.records;


import java.time.LocalDateTime;

import kr.co.common.jooq.tables.Role;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RoleRecord extends UpdatableRecordImpl<RoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.role.role_id</code>.
     */
    public RoleRecord setRoleId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.role.role_id</code>.
     */
    public Integer getRoleId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.role.role_name</code>.
     */
    public RoleRecord setRoleName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.role.role_name</code>.
     */
    public String getRoleName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.role.level</code>.
     */
    public RoleRecord setLevel(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.role.level</code>.
     */
    public Integer getLevel() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.role.create_date</code>.
     */
    public RoleRecord setCreateDate(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.role.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.role.create_user_id</code>.
     */
    public RoleRecord setCreateUserId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.role.create_user_id</code>.
     */
    public Long getCreateUserId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.role.update_date</code>.
     */
    public RoleRecord setUpdateDate(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.role.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.role.update_user_id</code>.
     */
    public RoleRecord setUpdateUserId(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.role.update_user_id</code>.
     */
    public Long getUpdateUserId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.role.delete_date</code>.
     */
    public RoleRecord setDeleteDate(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.role.delete_date</code>.
     */
    public LocalDateTime getDeleteDate() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.role.is_default</code>.
     */
    public RoleRecord setIsDefault(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.role.is_default</code>.
     */
    public String getIsDefault() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.role.delete_user_id</code>.
     */
    public RoleRecord setDeleteUserId(Long value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.role.delete_user_id</code>.
     */
    public Long getDeleteUserId() {
        return (Long) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoleRecord
     */
    public RoleRecord() {
        super(Role.ROLE);
    }

    /**
     * Create a detached, initialised RoleRecord
     */
    public RoleRecord(Integer roleId, String roleName, Integer level, LocalDateTime createDate, Long createUserId, LocalDateTime updateDate, Long updateUserId, LocalDateTime deleteDate, String isDefault, Long deleteUserId) {
        super(Role.ROLE);

        setRoleId(roleId);
        setRoleName(roleName);
        setLevel(level);
        setCreateDate(createDate);
        setCreateUserId(createUserId);
        setUpdateDate(updateDate);
        setUpdateUserId(updateUserId);
        setDeleteDate(deleteDate);
        setIsDefault(isDefault);
        setDeleteUserId(deleteUserId);
        resetChangedOnNotNull();
    }
}
