/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables.records;


import java.time.LocalDateTime;

import kr.co.common.jooq.tables.Species;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SpeciesRecord extends UpdatableRecordImpl<SpeciesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.species.species_id</code>.
     */
    public SpeciesRecord setSpeciesId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.species.species_id</code>.
     */
    public Integer getSpeciesId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.species.name</code>.
     */
    public SpeciesRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.species.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.species.create_date</code>.
     */
    public SpeciesRecord setCreateDate(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.species.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.species.create_user_id</code>.
     */
    public SpeciesRecord setCreateUserId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.species.create_user_id</code>.
     */
    public Long getCreateUserId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.species.update_date</code>.
     */
    public SpeciesRecord setUpdateDate(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.species.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.species.update_user_id</code>.
     */
    public SpeciesRecord setUpdateUserId(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.species.update_user_id</code>.
     */
    public Long getUpdateUserId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.species.delete_date</code>.
     */
    public SpeciesRecord setDeleteDate(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.species.delete_date</code>.
     */
    public LocalDateTime getDeleteDate() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.species.delete_user_id</code>.
     */
    public SpeciesRecord setDeleteUserId(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.species.delete_user_id</code>.
     */
    public Long getDeleteUserId() {
        return (Long) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpeciesRecord
     */
    public SpeciesRecord() {
        super(Species.SPECIES);
    }

    /**
     * Create a detached, initialised SpeciesRecord
     */
    public SpeciesRecord(Integer speciesId, String name, LocalDateTime createDate, Long createUserId, LocalDateTime updateDate, Long updateUserId, LocalDateTime deleteDate, Long deleteUserId) {
        super(Species.SPECIES);

        setSpeciesId(speciesId);
        setName(name);
        setCreateDate(createDate);
        setCreateUserId(createUserId);
        setUpdateDate(updateDate);
        setUpdateUserId(updateUserId);
        setDeleteDate(deleteDate);
        setDeleteUserId(deleteUserId);
        resetChangedOnNotNull();
    }
}
