/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables.records;


import java.time.LocalDateTime;

import kr.co.common.jooq.tables.UserVoteCount;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserVoteCountRecord extends UpdatableRecordImpl<UserVoteCountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_vote_count.user_id</code>.
     */
    public UserVoteCountRecord setUserId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.user_vote_count.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.user_vote_count.create_date</code>.
     */
    public UserVoteCountRecord setCreateDate(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.user_vote_count.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.user_vote_count.create_user_id</code>.
     */
    public UserVoteCountRecord setCreateUserId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.user_vote_count.create_user_id</code>.
     */
    public Long getCreateUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.user_vote_count.update_date</code>.
     */
    public UserVoteCountRecord setUpdateDate(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.user_vote_count.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.user_vote_count.update_user_id</code>.
     */
    public UserVoteCountRecord setUpdateUserId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.user_vote_count.update_user_id</code>.
     */
    public Long getUpdateUserId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.user_vote_count.vote_count</code>.
     */
    public UserVoteCountRecord setVoteCount(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.user_vote_count.vote_count</code>.
     */
    public Integer getVoteCount() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserVoteCountRecord
     */
    public UserVoteCountRecord() {
        super(UserVoteCount.USER_VOTE_COUNT);
    }

    /**
     * Create a detached, initialised UserVoteCountRecord
     */
    public UserVoteCountRecord(Long userId, LocalDateTime createDate, Long createUserId, LocalDateTime updateDate, Long updateUserId, Integer voteCount) {
        super(UserVoteCount.USER_VOTE_COUNT);

        setUserId(userId);
        setCreateDate(createDate);
        setCreateUserId(createUserId);
        setUpdateDate(updateDate);
        setUpdateUserId(updateUserId);
        setVoteCount(voteCount);
        resetChangedOnNotNull();
    }
}
