/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables.records;


import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import kr.co.common.jooq.enums.UserLoginTypeEnum;
import kr.co.common.jooq.tables.User;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user.user_id</code>.
     */
    public UserRecord setUserId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.user.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.user.email</code>.
     */
    public UserRecord setEmail(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.user.email</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.user.user_uuid</code>.
     */
    public UserRecord setUserUuid(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.user.user_uuid</code>.
     */
    public String getUserUuid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.user.password</code>.
     */
    public UserRecord setPassword(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.user.password</code>.
     */
    public String getPassword() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.user.role_id</code>.
     */
    public UserRecord setRoleId(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.user.role_id</code>.
     */
    public Integer getRoleId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.user.name</code>.
     */
    public UserRecord setName(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.user.name</code>.
     */
    public String getName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.user.nickname</code>.
     */
    public UserRecord setNickname(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.user.nickname</code>.
     */
    public String getNickname() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.user.phone_number</code>.
     */
    public UserRecord setPhoneNumber(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.user.phone_number</code>.
     */
    public String getPhoneNumber() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.user.birth_date</code>.
     */
    public UserRecord setBirthDate(LocalDate value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.user.birth_date</code>.
     */
    public LocalDate getBirthDate() {
        return (LocalDate) get(8);
    }

    /**
     * Setter for <code>public.user.gender</code>.
     */
    public UserRecord setGender(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.user.gender</code>.
     */
    public String getGender() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.user.height</code>.
     */
    public UserRecord setHeight(BigDecimal value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.user.height</code>.
     */
    public BigDecimal getHeight() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>public.user.weight</code>.
     */
    public UserRecord setWeight(BigDecimal value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.user.weight</code>.
     */
    public BigDecimal getWeight() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>public.user.login_type</code>.
     */
    public UserRecord setLoginType(UserLoginTypeEnum value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.user.login_type</code>.
     */
    public UserLoginTypeEnum getLoginType() {
        return (UserLoginTypeEnum) get(12);
    }

    /**
     * Setter for <code>public.user.login_id</code>.
     */
    public UserRecord setLoginId(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.user.login_id</code>.
     */
    public String getLoginId() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.user.is_email_verified</code>.
     */
    public UserRecord setIsEmailVerified(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.user.is_email_verified</code>.
     */
    public String getIsEmailVerified() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.user.company_id</code>.
     */
    public UserRecord setCompanyId(Integer value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>public.user.company_id</code>.
     */
    public Integer getCompanyId() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>public.user.description</code>.
     */
    public UserRecord setDescription(String value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>public.user.description</code>.
     */
    public String getDescription() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.user.create_date</code>.
     */
    public UserRecord setCreateDate(LocalDateTime value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>public.user.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(17);
    }

    /**
     * Setter for <code>public.user.create_user_id</code>.
     */
    public UserRecord setCreateUserId(Long value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>public.user.create_user_id</code>.
     */
    public Long getCreateUserId() {
        return (Long) get(18);
    }

    /**
     * Setter for <code>public.user.update_date</code>.
     */
    public UserRecord setUpdateDate(LocalDateTime value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>public.user.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(19);
    }

    /**
     * Setter for <code>public.user.update_user_id</code>.
     */
    public UserRecord setUpdateUserId(Long value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>public.user.update_user_id</code>.
     */
    public Long getUpdateUserId() {
        return (Long) get(20);
    }

    /**
     * Setter for <code>public.user.delete_date</code>.
     */
    public UserRecord setDeleteDate(LocalDateTime value) {
        set(21, value);
        return this;
    }

    /**
     * Getter for <code>public.user.delete_date</code>.
     */
    public LocalDateTime getDeleteDate() {
        return (LocalDateTime) get(21);
    }

    /**
     * Setter for <code>public.user.is_phone_number_verified</code>.
     */
    public UserRecord setIsPhoneNumberVerified(String value) {
        set(22, value);
        return this;
    }

    /**
     * Getter for <code>public.user.is_phone_number_verified</code>.
     */
    public String getIsPhoneNumberVerified() {
        return (String) get(22);
    }

    /**
     * Setter for <code>public.user.delete_user_id</code>.
     */
    public UserRecord setDeleteUserId(Long value) {
        set(23, value);
        return this;
    }

    /**
     * Getter for <code>public.user.delete_user_id</code>.
     */
    public Long getDeleteUserId() {
        return (Long) get(23);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Long userId, String email, String userUuid, String password, Integer roleId, String name, String nickname, String phoneNumber, LocalDate birthDate, String gender, BigDecimal height, BigDecimal weight, UserLoginTypeEnum loginType, String loginId, String isEmailVerified, Integer companyId, String description, LocalDateTime createDate, Long createUserId, LocalDateTime updateDate, Long updateUserId, LocalDateTime deleteDate, String isPhoneNumberVerified, Long deleteUserId) {
        super(User.USER);

        setUserId(userId);
        setEmail(email);
        setUserUuid(userUuid);
        setPassword(password);
        setRoleId(roleId);
        setName(name);
        setNickname(nickname);
        setPhoneNumber(phoneNumber);
        setBirthDate(birthDate);
        setGender(gender);
        setHeight(height);
        setWeight(weight);
        setLoginType(loginType);
        setLoginId(loginId);
        setIsEmailVerified(isEmailVerified);
        setCompanyId(companyId);
        setDescription(description);
        setCreateDate(createDate);
        setCreateUserId(createUserId);
        setUpdateDate(updateDate);
        setUpdateUserId(updateUserId);
        setDeleteDate(deleteDate);
        setIsPhoneNumberVerified(isPhoneNumberVerified);
        setDeleteUserId(deleteUserId);
        resetChangedOnNotNull();
    }
}
