/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables.records;


import java.time.LocalDateTime;

import kr.co.common.jooq.tables.UserVoteCountHistory;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserVoteCountHistoryRecord extends UpdatableRecordImpl<UserVoteCountHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_vote_count_history.history_id</code>.
     */
    public UserVoteCountHistoryRecord setHistoryId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.user_vote_count_history.history_id</code>.
     */
    public Long getHistoryId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.user_vote_count_history.create_date</code>.
     */
    public UserVoteCountHistoryRecord setCreateDate(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.user_vote_count_history.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.user_vote_count_history.create_user_id</code>.
     */
    public UserVoteCountHistoryRecord setCreateUserId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.user_vote_count_history.create_user_id</code>.
     */
    public Long getCreateUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.user_vote_count_history.user_id</code>.
     */
    public UserVoteCountHistoryRecord setUserId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.user_vote_count_history.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.user_vote_count_history.change_amount</code>.
     */
    public UserVoteCountHistoryRecord setChangeAmount(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.user_vote_count_history.change_amount</code>.
     */
    public Integer getChangeAmount() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.user_vote_count_history.before_count</code>.
     */
    public UserVoteCountHistoryRecord setBeforeCount(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.user_vote_count_history.before_count</code>.
     */
    public Integer getBeforeCount() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.user_vote_count_history.after_count</code>.
     */
    public UserVoteCountHistoryRecord setAfterCount(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.user_vote_count_history.after_count</code>.
     */
    public Integer getAfterCount() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserVoteCountHistoryRecord
     */
    public UserVoteCountHistoryRecord() {
        super(UserVoteCountHistory.USER_VOTE_COUNT_HISTORY);
    }

    /**
     * Create a detached, initialised UserVoteCountHistoryRecord
     */
    public UserVoteCountHistoryRecord(Long historyId, LocalDateTime createDate, Long createUserId, Long userId, Integer changeAmount, Integer beforeCount, Integer afterCount) {
        super(UserVoteCountHistory.USER_VOTE_COUNT_HISTORY);

        setHistoryId(historyId);
        setCreateDate(createDate);
        setCreateUserId(createUserId);
        setUserId(userId);
        setChangeAmount(changeAmount);
        setBeforeCount(beforeCount);
        setAfterCount(afterCount);
        resetChangedOnNotNull();
    }
}
