/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables.records;


import java.time.LocalDate;
import java.time.LocalDateTime;

import kr.co.common.jooq.tables.VoteWeekly;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VoteWeeklyRecord extends UpdatableRecordImpl<VoteWeeklyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.vote_weekly.vote_weekly_id</code>.
     */
    public VoteWeeklyRecord setVoteWeeklyId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.vote_weekly.vote_weekly_id</code>.
     */
    public Long getVoteWeeklyId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.vote_weekly.create_date</code>.
     */
    public VoteWeeklyRecord setCreateDate(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.vote_weekly.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.vote_weekly.create_user_id</code>.
     */
    public VoteWeeklyRecord setCreateUserId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.vote_weekly.create_user_id</code>.
     */
    public Long getCreateUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.vote_weekly.update_date</code>.
     */
    public VoteWeeklyRecord setUpdateDate(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.vote_weekly.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.vote_weekly.update_user_id</code>.
     */
    public VoteWeeklyRecord setUpdateUserId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.vote_weekly.update_user_id</code>.
     */
    public Long getUpdateUserId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.vote_weekly.delete_date</code>.
     */
    public VoteWeeklyRecord setDeleteDate(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.vote_weekly.delete_date</code>.
     */
    public LocalDateTime getDeleteDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.vote_weekly.delete_user_id</code>.
     */
    public VoteWeeklyRecord setDeleteUserId(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.vote_weekly.delete_user_id</code>.
     */
    public Long getDeleteUserId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.vote_weekly.week_start_date</code>.
     */
    public VoteWeeklyRecord setWeekStartDate(LocalDate value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.vote_weekly.week_start_date</code>.
     */
    public LocalDate getWeekStartDate() {
        return (LocalDate) get(7);
    }

    /**
     * Setter for <code>public.vote_weekly.pet_id</code>.
     */
    public VoteWeeklyRecord setPetId(Long value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.vote_weekly.pet_id</code>.
     */
    public Long getPetId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.vote_weekly.vote_count</code>.
     */
    public VoteWeeklyRecord setVoteCount(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.vote_weekly.vote_count</code>.
     */
    public Integer getVoteCount() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.vote_weekly.view_count</code>.
     */
    public VoteWeeklyRecord setViewCount(Long value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.vote_weekly.view_count</code>.
     */
    public Long getViewCount() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>public.vote_weekly.mode_id</code>.
     */
    public VoteWeeklyRecord setModeId(Integer value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.vote_weekly.mode_id</code>.
     */
    public Integer getModeId() {
        return (Integer) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VoteWeeklyRecord
     */
    public VoteWeeklyRecord() {
        super(VoteWeekly.VOTE_WEEKLY);
    }

    /**
     * Create a detached, initialised VoteWeeklyRecord
     */
    public VoteWeeklyRecord(Long voteWeeklyId, LocalDateTime createDate, Long createUserId, LocalDateTime updateDate, Long updateUserId, LocalDateTime deleteDate, Long deleteUserId, LocalDate weekStartDate, Long petId, Integer voteCount, Long viewCount, Integer modeId) {
        super(VoteWeekly.VOTE_WEEKLY);

        setVoteWeeklyId(voteWeeklyId);
        setCreateDate(createDate);
        setCreateUserId(createUserId);
        setUpdateDate(updateDate);
        setUpdateUserId(updateUserId);
        setDeleteDate(deleteDate);
        setDeleteUserId(deleteUserId);
        setWeekStartDate(weekStartDate);
        setPetId(petId);
        setVoteCount(voteCount);
        setViewCount(viewCount);
        setModeId(modeId);
        resetChangedOnNotNull();
    }
}
