/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables.records;


import java.time.LocalDate;
import java.time.LocalDateTime;

import kr.co.common.jooq.enums.VoteCycleType;
import kr.co.common.jooq.tables.VoteHistory;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VoteHistoryRecord extends UpdatableRecordImpl<VoteHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.vote_history.vote_history_id</code>.
     */
    public VoteHistoryRecord setVoteHistoryId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.vote_history.vote_history_id</code>.
     */
    public Long getVoteHistoryId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.vote_history.create_date</code>.
     */
    public VoteHistoryRecord setCreateDate(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.vote_history.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.vote_history.user_id</code>.
     */
    public VoteHistoryRecord setUserId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.vote_history.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.vote_history.vote_id</code>.
     */
    public VoteHistoryRecord setVoteId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.vote_history.vote_id</code>.
     */
    public Long getVoteId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.vote_history.history_date</code>.
     */
    public VoteHistoryRecord setHistoryDate(LocalDate value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.vote_history.history_date</code>.
     */
    public LocalDate getHistoryDate() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>public.vote_history.email</code>.
     */
    public VoteHistoryRecord setEmail(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.vote_history.email</code>.
     */
    public String getEmail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.vote_history.vote_cycle</code>.
     */
    public VoteHistoryRecord setVoteCycle(VoteCycleType value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.vote_history.vote_cycle</code>.
     */
    public VoteCycleType getVoteCycle() {
        return (VoteCycleType) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VoteHistoryRecord
     */
    public VoteHistoryRecord() {
        super(VoteHistory.VOTE_HISTORY);
    }

    /**
     * Create a detached, initialised VoteHistoryRecord
     */
    public VoteHistoryRecord(Long voteHistoryId, LocalDateTime createDate, Long userId, Long voteId, LocalDate historyDate, String email, VoteCycleType voteCycle) {
        super(VoteHistory.VOTE_HISTORY);

        setVoteHistoryId(voteHistoryId);
        setCreateDate(createDate);
        setUserId(userId);
        setVoteId(voteId);
        setHistoryDate(historyDate);
        setEmail(email);
        setVoteCycle(voteCycle);
        resetChangedOnNotNull();
    }
}
