/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import kr.co.common.jooq.Keys;
import kr.co.common.jooq.Public;
import kr.co.common.jooq.tables.Pet.PetPath;
import kr.co.common.jooq.tables.Species.SpeciesPath;
import kr.co.common.jooq.tables.records.BreedRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Breed extends TableImpl<BreedRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.breed</code>
     */
    public static final Breed BREED = new Breed();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BreedRecord> getRecordType() {
        return BreedRecord.class;
    }

    /**
     * The column <code>public.breed.breed_id</code>.
     */
    public final TableField<BreedRecord, Integer> BREED_ID = createField(DSL.name("breed_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.breed.species_id</code>.
     */
    public final TableField<BreedRecord, Long> SPECIES_ID = createField(DSL.name("species_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.breed.name</code>.
     */
    public final TableField<BreedRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.breed.create_date</code>.
     */
    public final TableField<BreedRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("create_date"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.breed.create_user_id</code>.
     */
    public final TableField<BreedRecord, Long> CREATE_USER_ID = createField(DSL.name("create_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.breed.update_date</code>.
     */
    public final TableField<BreedRecord, LocalDateTime> UPDATE_DATE = createField(DSL.name("update_date"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.breed.update_user_id</code>.
     */
    public final TableField<BreedRecord, Long> UPDATE_USER_ID = createField(DSL.name("update_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.breed.delete_date</code>.
     */
    public final TableField<BreedRecord, LocalDateTime> DELETE_DATE = createField(DSL.name("delete_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.breed.delete_user_id</code>.
     */
    public final TableField<BreedRecord, Long> DELETE_USER_ID = createField(DSL.name("delete_user_id"), SQLDataType.BIGINT, this, "");

    private Breed(Name alias, Table<BreedRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Breed(Name alias, Table<BreedRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.breed</code> table reference
     */
    public Breed(String alias) {
        this(DSL.name(alias), BREED);
    }

    /**
     * Create an aliased <code>public.breed</code> table reference
     */
    public Breed(Name alias) {
        this(alias, BREED);
    }

    /**
     * Create a <code>public.breed</code> table reference
     */
    public Breed() {
        this(DSL.name("breed"), null);
    }

    public <O extends Record> Breed(Table<O> path, ForeignKey<O, BreedRecord> childPath, InverseForeignKey<O, BreedRecord> parentPath) {
        super(path, childPath, parentPath, BREED);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class BreedPath extends Breed implements Path<BreedRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> BreedPath(Table<O> path, ForeignKey<O, BreedRecord> childPath, InverseForeignKey<O, BreedRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private BreedPath(Name alias, Table<BreedRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public BreedPath as(String alias) {
            return new BreedPath(DSL.name(alias), this);
        }

        @Override
        public BreedPath as(Name alias) {
            return new BreedPath(alias, this);
        }

        @Override
        public BreedPath as(Table<?> alias) {
            return new BreedPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<BreedRecord> getPrimaryKey() {
        return Keys.BREED_PKEY;
    }

    @Override
    public List<ForeignKey<BreedRecord, ?>> getReferences() {
        return Arrays.asList(Keys.BREED__BREED_SPECIES_ID_FKEY);
    }

    private transient SpeciesPath _species;

    /**
     * Get the implicit join path to the <code>public.species</code> table.
     */
    public SpeciesPath species() {
        if (_species == null)
            _species = new SpeciesPath(this, Keys.BREED__BREED_SPECIES_ID_FKEY, null);

        return _species;
    }

    private transient PetPath _pet;

    /**
     * Get the implicit to-many join path to the <code>public.pet</code> table
     */
    public PetPath pet() {
        if (_pet == null)
            _pet = new PetPath(this, null, Keys.PET__PET_BREED_ID_FKEY.getInverseKey());

        return _pet;
    }

    @Override
    public Breed as(String alias) {
        return new Breed(DSL.name(alias), this);
    }

    @Override
    public Breed as(Name alias) {
        return new Breed(alias, this);
    }

    @Override
    public Breed as(Table<?> alias) {
        return new Breed(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Breed rename(String name) {
        return new Breed(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Breed rename(Name name) {
        return new Breed(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Breed rename(Table<?> name) {
        return new Breed(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Breed where(Condition condition) {
        return new Breed(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Breed where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Breed where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Breed where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Breed where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Breed where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Breed where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Breed where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Breed whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Breed whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
