/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import kr.co.common.jooq.Keys;
import kr.co.common.jooq.Public;
import kr.co.common.jooq.enums.CommunityCategoryEnum;
import kr.co.common.jooq.tables.records.CommunityPostRecord;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CommunityPost extends TableImpl<CommunityPostRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.community_post</code>
     */
    public static final CommunityPost COMMUNITY_POST = new CommunityPost();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CommunityPostRecord> getRecordType() {
        return CommunityPostRecord.class;
    }

    /**
     * The column <code>public.community_post.post_id</code>.
     */
    public final TableField<CommunityPostRecord, Long> POST_ID = createField(DSL.name("post_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.community_post.create_date</code>.
     */
    public final TableField<CommunityPostRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("create_date"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.community_post.create_user_id</code>.
     */
    public final TableField<CommunityPostRecord, Long> CREATE_USER_ID = createField(DSL.name("create_user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.community_post.update_date</code>.
     */
    public final TableField<CommunityPostRecord, LocalDateTime> UPDATE_DATE = createField(DSL.name("update_date"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.community_post.update_user_id</code>.
     */
    public final TableField<CommunityPostRecord, Long> UPDATE_USER_ID = createField(DSL.name("update_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.community_post.delete_date</code>.
     */
    public final TableField<CommunityPostRecord, LocalDateTime> DELETE_DATE = createField(DSL.name("delete_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.community_post.delete_user_id</code>.
     */
    public final TableField<CommunityPostRecord, Long> DELETE_USER_ID = createField(DSL.name("delete_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.community_post.user_id</code>.
     */
    public final TableField<CommunityPostRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.community_post.title</code>.
     */
    public final TableField<CommunityPostRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.community_post.content</code>.
     */
    public final TableField<CommunityPostRecord, String> CONTENT = createField(DSL.name("content"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.community_post.content_type</code>.
     */
    public final TableField<CommunityPostRecord, String> CONTENT_TYPE = createField(DSL.name("content_type"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.community_post.view_count</code>.
     */
    public final TableField<CommunityPostRecord, Long> VIEW_COUNT = createField(DSL.name("view_count"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.community_post.like_count</code>.
     */
    public final TableField<CommunityPostRecord, Long> LIKE_COUNT = createField(DSL.name("like_count"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.community_post.comment_count</code>.
     */
    public final TableField<CommunityPostRecord, Long> COMMENT_COUNT = createField(DSL.name("comment_count"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.community_post.is_pinned</code>.
     */
    public final TableField<CommunityPostRecord, String> IS_PINNED = createField(DSL.name("is_pinned"), SQLDataType.CHAR(1).defaultValue(DSL.field(DSL.raw("'N'::bpchar"), SQLDataType.CHAR)), this, "");

    /**
     * The column <code>public.community_post.pin_order</code>.
     */
    public final TableField<CommunityPostRecord, Integer> PIN_ORDER = createField(DSL.name("pin_order"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.community_post.category</code>.
     */
    public final TableField<CommunityPostRecord, CommunityCategoryEnum> CATEGORY = createField(DSL.name("category"), SQLDataType.VARCHAR.asEnumDataType(CommunityCategoryEnum.class), this, "");

    private CommunityPost(Name alias, Table<CommunityPostRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CommunityPost(Name alias, Table<CommunityPostRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.community_post</code> table reference
     */
    public CommunityPost(String alias) {
        this(DSL.name(alias), COMMUNITY_POST);
    }

    /**
     * Create an aliased <code>public.community_post</code> table reference
     */
    public CommunityPost(Name alias) {
        this(alias, COMMUNITY_POST);
    }

    /**
     * Create a <code>public.community_post</code> table reference
     */
    public CommunityPost() {
        this(DSL.name("community_post"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<CommunityPostRecord, Long> getIdentity() {
        return (Identity<CommunityPostRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<CommunityPostRecord> getPrimaryKey() {
        return Keys.COMMUNITY_POST_PKEY;
    }

    @Override
    public List<Check<CommunityPostRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("community_post_content_type_check"), "(((content_type)::text = ANY ((ARRAY['TEXT'::character varying, 'HTML'::character varying])::text[])))", true)
        );
    }

    @Override
    public CommunityPost as(String alias) {
        return new CommunityPost(DSL.name(alias), this);
    }

    @Override
    public CommunityPost as(Name alias) {
        return new CommunityPost(alias, this);
    }

    @Override
    public CommunityPost as(Table<?> alias) {
        return new CommunityPost(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CommunityPost rename(String name) {
        return new CommunityPost(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CommunityPost rename(Name name) {
        return new CommunityPost(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CommunityPost rename(Table<?> name) {
        return new CommunityPost(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CommunityPost where(Condition condition) {
        return new CommunityPost(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CommunityPost where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CommunityPost where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CommunityPost where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CommunityPost where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CommunityPost where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CommunityPost where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CommunityPost where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CommunityPost whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CommunityPost whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
