/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables;


import java.time.LocalDateTime;
import java.util.Collection;

import kr.co.common.jooq.Keys;
import kr.co.common.jooq.Public;
import kr.co.common.jooq.tables.records.CommunityCommentRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CommunityComment extends TableImpl<CommunityCommentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.community_comment</code>
     */
    public static final CommunityComment COMMUNITY_COMMENT = new CommunityComment();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CommunityCommentRecord> getRecordType() {
        return CommunityCommentRecord.class;
    }

    /**
     * The column <code>public.community_comment.comment_id</code>.
     */
    public final TableField<CommunityCommentRecord, Long> COMMENT_ID = createField(DSL.name("comment_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.community_comment.create_date</code>.
     */
    public final TableField<CommunityCommentRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("create_date"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.community_comment.create_user_id</code>.
     */
    public final TableField<CommunityCommentRecord, Long> CREATE_USER_ID = createField(DSL.name("create_user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.community_comment.update_date</code>.
     */
    public final TableField<CommunityCommentRecord, LocalDateTime> UPDATE_DATE = createField(DSL.name("update_date"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.community_comment.update_user_id</code>.
     */
    public final TableField<CommunityCommentRecord, Long> UPDATE_USER_ID = createField(DSL.name("update_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.community_comment.delete_date</code>.
     */
    public final TableField<CommunityCommentRecord, LocalDateTime> DELETE_DATE = createField(DSL.name("delete_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.community_comment.delete_user_id</code>.
     */
    public final TableField<CommunityCommentRecord, Long> DELETE_USER_ID = createField(DSL.name("delete_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.community_comment.post_id</code>.
     */
    public final TableField<CommunityCommentRecord, Long> POST_ID = createField(DSL.name("post_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.community_comment.user_id</code>.
     */
    public final TableField<CommunityCommentRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.community_comment.content</code>.
     */
    public final TableField<CommunityCommentRecord, String> CONTENT = createField(DSL.name("content"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.community_comment.like_count</code>.
     */
    public final TableField<CommunityCommentRecord, Long> LIKE_COUNT = createField(DSL.name("like_count"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.community_comment.parent_comment_id</code>.
     */
    public final TableField<CommunityCommentRecord, Long> PARENT_COMMENT_ID = createField(DSL.name("parent_comment_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.community_comment.depth</code>.
     */
    public final TableField<CommunityCommentRecord, Integer> DEPTH = createField(DSL.name("depth"), SQLDataType.INTEGER, this, "");

    private CommunityComment(Name alias, Table<CommunityCommentRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CommunityComment(Name alias, Table<CommunityCommentRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.community_comment</code> table reference
     */
    public CommunityComment(String alias) {
        this(DSL.name(alias), COMMUNITY_COMMENT);
    }

    /**
     * Create an aliased <code>public.community_comment</code> table reference
     */
    public CommunityComment(Name alias) {
        this(alias, COMMUNITY_COMMENT);
    }

    /**
     * Create a <code>public.community_comment</code> table reference
     */
    public CommunityComment() {
        this(DSL.name("community_comment"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<CommunityCommentRecord, Long> getIdentity() {
        return (Identity<CommunityCommentRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<CommunityCommentRecord> getPrimaryKey() {
        return Keys.COMMUNITY_COMMENT_PKEY;
    }

    @Override
    public CommunityComment as(String alias) {
        return new CommunityComment(DSL.name(alias), this);
    }

    @Override
    public CommunityComment as(Name alias) {
        return new CommunityComment(alias, this);
    }

    @Override
    public CommunityComment as(Table<?> alias) {
        return new CommunityComment(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CommunityComment rename(String name) {
        return new CommunityComment(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CommunityComment rename(Name name) {
        return new CommunityComment(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CommunityComment rename(Table<?> name) {
        return new CommunityComment(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CommunityComment where(Condition condition) {
        return new CommunityComment(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CommunityComment where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CommunityComment where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CommunityComment where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CommunityComment where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CommunityComment where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CommunityComment where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CommunityComment where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CommunityComment whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CommunityComment whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
