/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables;


import java.time.LocalDateTime;
import java.util.Collection;

import kr.co.common.jooq.Keys;
import kr.co.common.jooq.Public;
import kr.co.common.jooq.tables.User.UserPath;
import kr.co.common.jooq.tables.records.CompanyRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Company extends TableImpl<CompanyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.company</code>
     */
    public static final Company COMPANY = new Company();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CompanyRecord> getRecordType() {
        return CompanyRecord.class;
    }

    /**
     * The column <code>public.company.company_id</code>.
     */
    public final TableField<CompanyRecord, Integer> COMPANY_ID = createField(DSL.name("company_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.company.company_name</code>.
     */
    public final TableField<CompanyRecord, String> COMPANY_NAME = createField(DSL.name("company_name"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.company.company_code</code>.
     */
    public final TableField<CompanyRecord, String> COMPANY_CODE = createField(DSL.name("company_code"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.company.address</code>.
     */
    public final TableField<CompanyRecord, String> ADDRESS = createField(DSL.name("address"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.company.phone_number</code>.
     */
    public final TableField<CompanyRecord, String> PHONE_NUMBER = createField(DSL.name("phone_number"), SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>public.company.create_date</code>.
     */
    public final TableField<CompanyRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("create_date"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.company.create_user_id</code>.
     */
    public final TableField<CompanyRecord, Long> CREATE_USER_ID = createField(DSL.name("create_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.company.update_date</code>.
     */
    public final TableField<CompanyRecord, LocalDateTime> UPDATE_DATE = createField(DSL.name("update_date"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.company.update_user_id</code>.
     */
    public final TableField<CompanyRecord, Long> UPDATE_USER_ID = createField(DSL.name("update_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.company.delete_date</code>.
     */
    public final TableField<CompanyRecord, LocalDateTime> DELETE_DATE = createField(DSL.name("delete_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.company.is_default</code>.
     */
    public final TableField<CompanyRecord, String> IS_DEFAULT = createField(DSL.name("is_default"), SQLDataType.CHAR(1).defaultValue(DSL.field(DSL.raw("'N'::bpchar"), SQLDataType.CHAR)), this, "");

    /**
     * The column <code>public.company.delete_user_id</code>.
     */
    public final TableField<CompanyRecord, Long> DELETE_USER_ID = createField(DSL.name("delete_user_id"), SQLDataType.BIGINT, this, "");

    private Company(Name alias, Table<CompanyRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Company(Name alias, Table<CompanyRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.company</code> table reference
     */
    public Company(String alias) {
        this(DSL.name(alias), COMPANY);
    }

    /**
     * Create an aliased <code>public.company</code> table reference
     */
    public Company(Name alias) {
        this(alias, COMPANY);
    }

    /**
     * Create a <code>public.company</code> table reference
     */
    public Company() {
        this(DSL.name("company"), null);
    }

    public <O extends Record> Company(Table<O> path, ForeignKey<O, CompanyRecord> childPath, InverseForeignKey<O, CompanyRecord> parentPath) {
        super(path, childPath, parentPath, COMPANY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CompanyPath extends Company implements Path<CompanyRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CompanyPath(Table<O> path, ForeignKey<O, CompanyRecord> childPath, InverseForeignKey<O, CompanyRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CompanyPath(Name alias, Table<CompanyRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CompanyPath as(String alias) {
            return new CompanyPath(DSL.name(alias), this);
        }

        @Override
        public CompanyPath as(Name alias) {
            return new CompanyPath(alias, this);
        }

        @Override
        public CompanyPath as(Table<?> alias) {
            return new CompanyPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<CompanyRecord> getPrimaryKey() {
        return Keys.COMPANY_PKEY;
    }

    private transient UserPath _user;

    /**
     * Get the implicit to-many join path to the <code>public.user</code> table
     */
    public UserPath user() {
        if (_user == null)
            _user = new UserPath(this, null, Keys.USER__USER_COMPANY_ID_FKEY.getInverseKey());

        return _user;
    }

    @Override
    public Company as(String alias) {
        return new Company(DSL.name(alias), this);
    }

    @Override
    public Company as(Name alias) {
        return new Company(alias, this);
    }

    @Override
    public Company as(Table<?> alias) {
        return new Company(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Company rename(String name) {
        return new Company(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Company rename(Name name) {
        return new Company(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Company rename(Table<?> name) {
        return new Company(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Company where(Condition condition) {
        return new Company(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Company where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Company where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Company where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Company where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Company where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Company where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Company where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Company whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Company whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
