/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables;


import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Collection;

import kr.co.common.jooq.Keys;
import kr.co.common.jooq.Public;
import kr.co.common.jooq.tables.records.EmailGuestRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EmailGuest extends TableImpl<EmailGuestRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.email_guest</code>
     */
    public static final EmailGuest EMAIL_GUEST = new EmailGuest();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EmailGuestRecord> getRecordType() {
        return EmailGuestRecord.class;
    }

    /**
     * The column <code>public.email_guest.email_guest_id</code>.
     */
    public final TableField<EmailGuestRecord, Long> EMAIL_GUEST_ID = createField(DSL.name("email_guest_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.email_guest.create_date</code>.
     */
    public final TableField<EmailGuestRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("create_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.email_guest.email</code>.
     */
    public final TableField<EmailGuestRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.email_guest.join_date</code>.
     */
    public final TableField<EmailGuestRecord, LocalDate> JOIN_DATE = createField(DSL.name("join_date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>public.email_guest.encrypte_token</code>.
     */
    public final TableField<EmailGuestRecord, String> ENCRYPTE_TOKEN = createField(DSL.name("encrypte_token"), SQLDataType.VARCHAR(200), this, "");

    private EmailGuest(Name alias, Table<EmailGuestRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private EmailGuest(Name alias, Table<EmailGuestRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.email_guest</code> table reference
     */
    public EmailGuest(String alias) {
        this(DSL.name(alias), EMAIL_GUEST);
    }

    /**
     * Create an aliased <code>public.email_guest</code> table reference
     */
    public EmailGuest(Name alias) {
        this(alias, EMAIL_GUEST);
    }

    /**
     * Create a <code>public.email_guest</code> table reference
     */
    public EmailGuest() {
        this(DSL.name("email_guest"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<EmailGuestRecord, Long> getIdentity() {
        return (Identity<EmailGuestRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<EmailGuestRecord> getPrimaryKey() {
        return Keys.EMAIL_GUEST_PK;
    }

    @Override
    public EmailGuest as(String alias) {
        return new EmailGuest(DSL.name(alias), this);
    }

    @Override
    public EmailGuest as(Name alias) {
        return new EmailGuest(alias, this);
    }

    @Override
    public EmailGuest as(Table<?> alias) {
        return new EmailGuest(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public EmailGuest rename(String name) {
        return new EmailGuest(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EmailGuest rename(Name name) {
        return new EmailGuest(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public EmailGuest rename(Table<?> name) {
        return new EmailGuest(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmailGuest where(Condition condition) {
        return new EmailGuest(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmailGuest where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmailGuest where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmailGuest where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmailGuest where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmailGuest where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmailGuest where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmailGuest where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmailGuest whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmailGuest whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
