/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import kr.co.common.jooq.Keys;
import kr.co.common.jooq.Public;
import kr.co.common.jooq.tables.User.UserPath;
import kr.co.common.jooq.tables.records.EmailVerificationRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EmailVerification extends TableImpl<EmailVerificationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.email_verification</code>
     */
    public static final EmailVerification EMAIL_VERIFICATION = new EmailVerification();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EmailVerificationRecord> getRecordType() {
        return EmailVerificationRecord.class;
    }

    /**
     * The column <code>public.email_verification.email_verification_id</code>.
     */
    public final TableField<EmailVerificationRecord, Long> EMAIL_VERIFICATION_ID = createField(DSL.name("email_verification_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.email_verification.user_id</code>.
     */
    public final TableField<EmailVerificationRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.email_verification.verification_code</code>.
     */
    public final TableField<EmailVerificationRecord, String> VERIFICATION_CODE = createField(DSL.name("verification_code"), SQLDataType.VARCHAR(6).nullable(false), this, "");

    /**
     * The column <code>public.email_verification.expires_date</code>.
     */
    public final TableField<EmailVerificationRecord, LocalDateTime> EXPIRES_DATE = createField(DSL.name("expires_date"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.email_verification.create_date</code>.
     */
    public final TableField<EmailVerificationRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("create_date"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.email_verification.create_user_id</code>.
     */
    public final TableField<EmailVerificationRecord, Long> CREATE_USER_ID = createField(DSL.name("create_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.email_verification.update_date</code>.
     */
    public final TableField<EmailVerificationRecord, LocalDateTime> UPDATE_DATE = createField(DSL.name("update_date"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.email_verification.update_user_id</code>.
     */
    public final TableField<EmailVerificationRecord, Long> UPDATE_USER_ID = createField(DSL.name("update_user_id"), SQLDataType.BIGINT, this, "");

    private EmailVerification(Name alias, Table<EmailVerificationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private EmailVerification(Name alias, Table<EmailVerificationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.email_verification</code> table reference
     */
    public EmailVerification(String alias) {
        this(DSL.name(alias), EMAIL_VERIFICATION);
    }

    /**
     * Create an aliased <code>public.email_verification</code> table reference
     */
    public EmailVerification(Name alias) {
        this(alias, EMAIL_VERIFICATION);
    }

    /**
     * Create a <code>public.email_verification</code> table reference
     */
    public EmailVerification() {
        this(DSL.name("email_verification"), null);
    }

    public <O extends Record> EmailVerification(Table<O> path, ForeignKey<O, EmailVerificationRecord> childPath, InverseForeignKey<O, EmailVerificationRecord> parentPath) {
        super(path, childPath, parentPath, EMAIL_VERIFICATION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class EmailVerificationPath extends EmailVerification implements Path<EmailVerificationRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> EmailVerificationPath(Table<O> path, ForeignKey<O, EmailVerificationRecord> childPath, InverseForeignKey<O, EmailVerificationRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private EmailVerificationPath(Name alias, Table<EmailVerificationRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public EmailVerificationPath as(String alias) {
            return new EmailVerificationPath(DSL.name(alias), this);
        }

        @Override
        public EmailVerificationPath as(Name alias) {
            return new EmailVerificationPath(alias, this);
        }

        @Override
        public EmailVerificationPath as(Table<?> alias) {
            return new EmailVerificationPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<EmailVerificationRecord, Long> getIdentity() {
        return (Identity<EmailVerificationRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<EmailVerificationRecord> getPrimaryKey() {
        return Keys.USER_EMAIL_VERIFICATION_PKEY;
    }

    @Override
    public List<ForeignKey<EmailVerificationRecord, ?>> getReferences() {
        return Arrays.asList(Keys.EMAIL_VERIFICATION__FK_USER);
    }

    private transient UserPath _user;

    /**
     * Get the implicit join path to the <code>public.user</code> table.
     */
    public UserPath user() {
        if (_user == null)
            _user = new UserPath(this, Keys.EMAIL_VERIFICATION__FK_USER, null);

        return _user;
    }

    @Override
    public EmailVerification as(String alias) {
        return new EmailVerification(DSL.name(alias), this);
    }

    @Override
    public EmailVerification as(Name alias) {
        return new EmailVerification(alias, this);
    }

    @Override
    public EmailVerification as(Table<?> alias) {
        return new EmailVerification(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public EmailVerification rename(String name) {
        return new EmailVerification(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EmailVerification rename(Name name) {
        return new EmailVerification(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public EmailVerification rename(Table<?> name) {
        return new EmailVerification(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmailVerification where(Condition condition) {
        return new EmailVerification(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmailVerification where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmailVerification where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmailVerification where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmailVerification where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmailVerification where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmailVerification where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmailVerification where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmailVerification whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmailVerification whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
