/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables;


import java.time.LocalDateTime;
import java.util.Collection;

import kr.co.common.jooq.Keys;
import kr.co.common.jooq.Public;
import kr.co.common.jooq.enums.FileTypeEnum;
import kr.co.common.jooq.enums.RefTableEnum;
import kr.co.common.jooq.tables.records.FileInfoRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FileInfo extends TableImpl<FileInfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.file_info</code>
     */
    public static final FileInfo FILE_INFO = new FileInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FileInfoRecord> getRecordType() {
        return FileInfoRecord.class;
    }

    /**
     * The column <code>public.file_info.file_id</code>.
     */
    public final TableField<FileInfoRecord, Long> FILE_ID = createField(DSL.name("file_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.file_info.create_date</code>.
     */
    public final TableField<FileInfoRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("create_date"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.file_info.create_user_id</code>.
     */
    public final TableField<FileInfoRecord, Long> CREATE_USER_ID = createField(DSL.name("create_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.file_info.updated_date</code>.
     */
    public final TableField<FileInfoRecord, LocalDateTime> UPDATED_DATE = createField(DSL.name("updated_date"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.file_info.update_user_id</code>.
     */
    public final TableField<FileInfoRecord, Long> UPDATE_USER_ID = createField(DSL.name("update_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.file_info.delete_date</code>.
     */
    public final TableField<FileInfoRecord, LocalDateTime> DELETE_DATE = createField(DSL.name("delete_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.file_info.delete_user_id</code>.
     */
    public final TableField<FileInfoRecord, Long> DELETE_USER_ID = createField(DSL.name("delete_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.file_info.ref_table</code>.
     */
    public final TableField<FileInfoRecord, RefTableEnum> REF_TABLE = createField(DSL.name("ref_table"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(RefTableEnum.class), this, "");

    /**
     * The column <code>public.file_info.ref_id</code>.
     */
    public final TableField<FileInfoRecord, Long> REF_ID = createField(DSL.name("ref_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.file_info.file_type</code>.
     */
    public final TableField<FileInfoRecord, FileTypeEnum> FILE_TYPE = createField(DSL.name("file_type"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(FileTypeEnum.class), this, "");

    /**
     * The column <code>public.file_info.sort_order</code>.
     */
    public final TableField<FileInfoRecord, Integer> SORT_ORDER = createField(DSL.name("sort_order"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.file_info.file_url</code>.
     */
    public final TableField<FileInfoRecord, String> FILE_URL = createField(DSL.name("file_url"), SQLDataType.VARCHAR(500).nullable(false), this, "");

    /**
     * The column <code>public.file_info.file_size</code>.
     */
    public final TableField<FileInfoRecord, Long> FILE_SIZE = createField(DSL.name("file_size"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.file_info.mime_type</code>.
     */
    public final TableField<FileInfoRecord, String> MIME_TYPE = createField(DSL.name("mime_type"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.file_info.file_name</code>.
     */
    public final TableField<FileInfoRecord, String> FILE_NAME = createField(DSL.name("file_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.file_info.original_file_name</code>.
     */
    public final TableField<FileInfoRecord, String> ORIGINAL_FILE_NAME = createField(DSL.name("original_file_name"), SQLDataType.VARCHAR(255), this, "");

    private FileInfo(Name alias, Table<FileInfoRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private FileInfo(Name alias, Table<FileInfoRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.file_info</code> table reference
     */
    public FileInfo(String alias) {
        this(DSL.name(alias), FILE_INFO);
    }

    /**
     * Create an aliased <code>public.file_info</code> table reference
     */
    public FileInfo(Name alias) {
        this(alias, FILE_INFO);
    }

    /**
     * Create a <code>public.file_info</code> table reference
     */
    public FileInfo() {
        this(DSL.name("file_info"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<FileInfoRecord, Long> getIdentity() {
        return (Identity<FileInfoRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FileInfoRecord> getPrimaryKey() {
        return Keys.FILE_INFO_PK;
    }

    @Override
    public FileInfo as(String alias) {
        return new FileInfo(DSL.name(alias), this);
    }

    @Override
    public FileInfo as(Name alias) {
        return new FileInfo(alias, this);
    }

    @Override
    public FileInfo as(Table<?> alias) {
        return new FileInfo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FileInfo rename(String name) {
        return new FileInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FileInfo rename(Name name) {
        return new FileInfo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FileInfo rename(Table<?> name) {
        return new FileInfo(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FileInfo where(Condition condition) {
        return new FileInfo(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FileInfo where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FileInfo where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FileInfo where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FileInfo where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FileInfo where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FileInfo where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FileInfo where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FileInfo whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FileInfo whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
