/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables;


import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import kr.co.common.jooq.Keys;
import kr.co.common.jooq.Public;
import kr.co.common.jooq.tables.records.GameScoreRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GameScore extends TableImpl<GameScoreRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.game_score</code>
     */
    public static final GameScore GAME_SCORE = new GameScore();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GameScoreRecord> getRecordType() {
        return GameScoreRecord.class;
    }

    /**
     * The column <code>public.game_score.score_id</code>.
     */
    public final TableField<GameScoreRecord, Long> SCORE_ID = createField(DSL.name("score_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.game_score.create_date</code>.
     */
    public final TableField<GameScoreRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("create_date"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.game_score.create_user_id</code>.
     */
    public final TableField<GameScoreRecord, Long> CREATE_USER_ID = createField(DSL.name("create_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.game_score.update_date</code>.
     */
    public final TableField<GameScoreRecord, LocalDateTime> UPDATE_DATE = createField(DSL.name("update_date"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.game_score.update_user_id</code>.
     */
    public final TableField<GameScoreRecord, Long> UPDATE_USER_ID = createField(DSL.name("update_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.game_score.user_id</code>.
     */
    public final TableField<GameScoreRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.game_score.week_start_date</code>.
     */
    public final TableField<GameScoreRecord, LocalDate> WEEK_START_DATE = createField(DSL.name("week_start_date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>public.game_score.score</code>.
     */
    public final TableField<GameScoreRecord, Double> SCORE = createField(DSL.name("score"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.game_score.pet_id</code>.
     */
    public final TableField<GameScoreRecord, Long> PET_ID = createField(DSL.name("pet_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private GameScore(Name alias, Table<GameScoreRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GameScore(Name alias, Table<GameScoreRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.game_score</code> table reference
     */
    public GameScore(String alias) {
        this(DSL.name(alias), GAME_SCORE);
    }

    /**
     * Create an aliased <code>public.game_score</code> table reference
     */
    public GameScore(Name alias) {
        this(alias, GAME_SCORE);
    }

    /**
     * Create a <code>public.game_score</code> table reference
     */
    public GameScore() {
        this(DSL.name("game_score"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<GameScoreRecord, Long> getIdentity() {
        return (Identity<GameScoreRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<GameScoreRecord> getPrimaryKey() {
        return Keys.GAME_SCORE_PK;
    }

    @Override
    public List<UniqueKey<GameScoreRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.GAME_SCORE_UNIQUE);
    }

    @Override
    public GameScore as(String alias) {
        return new GameScore(DSL.name(alias), this);
    }

    @Override
    public GameScore as(Name alias) {
        return new GameScore(alias, this);
    }

    @Override
    public GameScore as(Table<?> alias) {
        return new GameScore(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GameScore rename(String name) {
        return new GameScore(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GameScore rename(Name name) {
        return new GameScore(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GameScore rename(Table<?> name) {
        return new GameScore(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameScore where(Condition condition) {
        return new GameScore(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameScore where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameScore where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameScore where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GameScore where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GameScore where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GameScore where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GameScore where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameScore whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GameScore whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
