/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables;


import java.time.LocalDateTime;
import java.util.Collection;

import kr.co.common.jooq.Keys;
import kr.co.common.jooq.Public;
import kr.co.common.jooq.tables.Pet.PetPath;
import kr.co.common.jooq.tables.records.OwnershipRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Ownership extends TableImpl<OwnershipRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.ownership</code>
     */
    public static final Ownership OWNERSHIP = new Ownership();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OwnershipRecord> getRecordType() {
        return OwnershipRecord.class;
    }

    /**
     * The column <code>public.ownership.ownership_id</code>.
     */
    public final TableField<OwnershipRecord, Integer> OWNERSHIP_ID = createField(DSL.name("ownership_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.ownership.ownership_name</code>.
     */
    public final TableField<OwnershipRecord, String> OWNERSHIP_NAME = createField(DSL.name("ownership_name"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.ownership.create_date</code>.
     */
    public final TableField<OwnershipRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("create_date"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.ownership.create_user_id</code>.
     */
    public final TableField<OwnershipRecord, Long> CREATE_USER_ID = createField(DSL.name("create_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.ownership.update_date</code>.
     */
    public final TableField<OwnershipRecord, LocalDateTime> UPDATE_DATE = createField(DSL.name("update_date"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.ownership.update_user_id</code>.
     */
    public final TableField<OwnershipRecord, Long> UPDATE_USER_ID = createField(DSL.name("update_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.ownership.delete_date</code>.
     */
    public final TableField<OwnershipRecord, LocalDateTime> DELETE_DATE = createField(DSL.name("delete_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.ownership.delete_user_id</code>.
     */
    public final TableField<OwnershipRecord, Long> DELETE_USER_ID = createField(DSL.name("delete_user_id"), SQLDataType.BIGINT, this, "");

    private Ownership(Name alias, Table<OwnershipRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Ownership(Name alias, Table<OwnershipRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.ownership</code> table reference
     */
    public Ownership(String alias) {
        this(DSL.name(alias), OWNERSHIP);
    }

    /**
     * Create an aliased <code>public.ownership</code> table reference
     */
    public Ownership(Name alias) {
        this(alias, OWNERSHIP);
    }

    /**
     * Create a <code>public.ownership</code> table reference
     */
    public Ownership() {
        this(DSL.name("ownership"), null);
    }

    public <O extends Record> Ownership(Table<O> path, ForeignKey<O, OwnershipRecord> childPath, InverseForeignKey<O, OwnershipRecord> parentPath) {
        super(path, childPath, parentPath, OWNERSHIP);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class OwnershipPath extends Ownership implements Path<OwnershipRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> OwnershipPath(Table<O> path, ForeignKey<O, OwnershipRecord> childPath, InverseForeignKey<O, OwnershipRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private OwnershipPath(Name alias, Table<OwnershipRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public OwnershipPath as(String alias) {
            return new OwnershipPath(DSL.name(alias), this);
        }

        @Override
        public OwnershipPath as(Name alias) {
            return new OwnershipPath(alias, this);
        }

        @Override
        public OwnershipPath as(Table<?> alias) {
            return new OwnershipPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<OwnershipRecord> getPrimaryKey() {
        return Keys.OWNERSHIP_PKEY;
    }

    private transient PetPath _pet;

    /**
     * Get the implicit to-many join path to the <code>public.pet</code> table
     */
    public PetPath pet() {
        if (_pet == null)
            _pet = new PetPath(this, null, Keys.PET__PET_OWNERSHIP_ID_FKEY.getInverseKey());

        return _pet;
    }

    @Override
    public Ownership as(String alias) {
        return new Ownership(DSL.name(alias), this);
    }

    @Override
    public Ownership as(Name alias) {
        return new Ownership(alias, this);
    }

    @Override
    public Ownership as(Table<?> alias) {
        return new Ownership(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Ownership rename(String name) {
        return new Ownership(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Ownership rename(Name name) {
        return new Ownership(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Ownership rename(Table<?> name) {
        return new Ownership(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ownership where(Condition condition) {
        return new Ownership(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ownership where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ownership where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ownership where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Ownership where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Ownership where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Ownership where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Ownership where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ownership whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ownership whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
