/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables;


import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import kr.co.common.jooq.Keys;
import kr.co.common.jooq.Public;
import kr.co.common.jooq.tables.Breed.BreedPath;
import kr.co.common.jooq.tables.Ownership.OwnershipPath;
import kr.co.common.jooq.tables.User.UserPath;
import kr.co.common.jooq.tables.records.PetRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Pet extends TableImpl<PetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.pet</code>
     */
    public static final Pet PET = new Pet();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PetRecord> getRecordType() {
        return PetRecord.class;
    }

    /**
     * The column <code>public.pet.pet_id</code>.
     */
    public final TableField<PetRecord, Long> PET_ID = createField(DSL.name("pet_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.pet.breed_id</code>.
     */
    public final TableField<PetRecord, Long> BREED_ID = createField(DSL.name("breed_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.pet.custom_breed</code>.
     */
    public final TableField<PetRecord, String> CUSTOM_BREED = createField(DSL.name("custom_breed"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.pet.ownership_id</code>.
     */
    public final TableField<PetRecord, Long> OWNERSHIP_ID = createField(DSL.name("ownership_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.pet.user_id</code>.
     */
    public final TableField<PetRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.pet.name</code>.
     */
    public final TableField<PetRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.pet.birth_date</code>.
     */
    public final TableField<PetRecord, LocalDate> BIRTH_DATE = createField(DSL.name("birth_date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.pet.gender</code>.
     */
    public final TableField<PetRecord, String> GENDER = createField(DSL.name("gender"), SQLDataType.CHAR(1), this, "");

    /**
     * The column <code>public.pet.weight</code>.
     */
    public final TableField<PetRecord, BigDecimal> WEIGHT = createField(DSL.name("weight"), SQLDataType.NUMERIC(5, 2), this, "");

    /**
     * The column <code>public.pet.height</code>.
     */
    public final TableField<PetRecord, BigDecimal> HEIGHT = createField(DSL.name("height"), SQLDataType.NUMERIC(5, 2), this, "");

    /**
     * The column <code>public.pet.is_neutered</code>.
     */
    public final TableField<PetRecord, String> IS_NEUTERED = createField(DSL.name("is_neutered"), SQLDataType.CHAR(1), this, "");

    /**
     * The column <code>public.pet.microchip_id</code>.
     */
    public final TableField<PetRecord, String> MICROCHIP_ID = createField(DSL.name("microchip_id"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.pet.description</code>.
     */
    public final TableField<PetRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>public.pet.create_date</code>.
     */
    public final TableField<PetRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("create_date"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.pet.create_user_id</code>.
     */
    public final TableField<PetRecord, Long> CREATE_USER_ID = createField(DSL.name("create_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.pet.update_date</code>.
     */
    public final TableField<PetRecord, LocalDateTime> UPDATE_DATE = createField(DSL.name("update_date"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.pet.update_user_id</code>.
     */
    public final TableField<PetRecord, Long> UPDATE_USER_ID = createField(DSL.name("update_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.pet.delete_date</code>.
     */
    public final TableField<PetRecord, LocalDateTime> DELETE_DATE = createField(DSL.name("delete_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.pet.delete_user_id</code>.
     */
    public final TableField<PetRecord, Long> DELETE_USER_ID = createField(DSL.name("delete_user_id"), SQLDataType.BIGINT, this, "");

    private Pet(Name alias, Table<PetRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Pet(Name alias, Table<PetRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.pet</code> table reference
     */
    public Pet(String alias) {
        this(DSL.name(alias), PET);
    }

    /**
     * Create an aliased <code>public.pet</code> table reference
     */
    public Pet(Name alias) {
        this(alias, PET);
    }

    /**
     * Create a <code>public.pet</code> table reference
     */
    public Pet() {
        this(DSL.name("pet"), null);
    }

    public <O extends Record> Pet(Table<O> path, ForeignKey<O, PetRecord> childPath, InverseForeignKey<O, PetRecord> parentPath) {
        super(path, childPath, parentPath, PET);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PetPath extends Pet implements Path<PetRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PetPath(Table<O> path, ForeignKey<O, PetRecord> childPath, InverseForeignKey<O, PetRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PetPath(Name alias, Table<PetRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PetPath as(String alias) {
            return new PetPath(DSL.name(alias), this);
        }

        @Override
        public PetPath as(Name alias) {
            return new PetPath(alias, this);
        }

        @Override
        public PetPath as(Table<?> alias) {
            return new PetPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<PetRecord, Long> getIdentity() {
        return (Identity<PetRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PetRecord> getPrimaryKey() {
        return Keys.PET_PKEY;
    }

    @Override
    public List<UniqueKey<PetRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.PET_MICROCHIP_ID_KEY);
    }

    @Override
    public List<ForeignKey<PetRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PET__PET_BREED_ID_FKEY, Keys.PET__PET_OWNERSHIP_ID_FKEY, Keys.PET__PET_USER_ID_FKEY);
    }

    private transient BreedPath _breed;

    /**
     * Get the implicit join path to the <code>public.breed</code> table.
     */
    public BreedPath breed() {
        if (_breed == null)
            _breed = new BreedPath(this, Keys.PET__PET_BREED_ID_FKEY, null);

        return _breed;
    }

    private transient OwnershipPath _ownership;

    /**
     * Get the implicit join path to the <code>public.ownership</code> table.
     */
    public OwnershipPath ownership() {
        if (_ownership == null)
            _ownership = new OwnershipPath(this, Keys.PET__PET_OWNERSHIP_ID_FKEY, null);

        return _ownership;
    }

    private transient UserPath _user;

    /**
     * Get the implicit join path to the <code>public.user</code> table.
     */
    public UserPath user() {
        if (_user == null)
            _user = new UserPath(this, Keys.PET__PET_USER_ID_FKEY, null);

        return _user;
    }

    @Override
    public Pet as(String alias) {
        return new Pet(DSL.name(alias), this);
    }

    @Override
    public Pet as(Name alias) {
        return new Pet(alias, this);
    }

    @Override
    public Pet as(Table<?> alias) {
        return new Pet(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Pet rename(String name) {
        return new Pet(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Pet rename(Name name) {
        return new Pet(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Pet rename(Table<?> name) {
        return new Pet(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Pet where(Condition condition) {
        return new Pet(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Pet where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Pet where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Pet where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Pet where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Pet where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Pet where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Pet where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Pet whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Pet whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
