/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables;


import java.time.LocalDateTime;
import java.util.Collection;

import kr.co.common.jooq.Keys;
import kr.co.common.jooq.Public;
import kr.co.common.jooq.tables.records.PetModeRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PetMode extends TableImpl<PetModeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.pet_mode</code>
     */
    public static final PetMode PET_MODE = new PetMode();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PetModeRecord> getRecordType() {
        return PetModeRecord.class;
    }

    /**
     * The column <code>public.pet_mode.pet_mode_id</code>.
     */
    public final TableField<PetModeRecord, Integer> PET_MODE_ID = createField(DSL.name("pet_mode_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.pet_mode.create_date</code>.
     */
    public final TableField<PetModeRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("create_date"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.pet_mode.create_user_id</code>.
     */
    public final TableField<PetModeRecord, Long> CREATE_USER_ID = createField(DSL.name("create_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.pet_mode.update_date</code>.
     */
    public final TableField<PetModeRecord, LocalDateTime> UPDATE_DATE = createField(DSL.name("update_date"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.pet_mode.update_user_id</code>.
     */
    public final TableField<PetModeRecord, Long> UPDATE_USER_ID = createField(DSL.name("update_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.pet_mode.delete_date</code>.
     */
    public final TableField<PetModeRecord, LocalDateTime> DELETE_DATE = createField(DSL.name("delete_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.pet_mode.delete_user_id</code>.
     */
    public final TableField<PetModeRecord, Long> DELETE_USER_ID = createField(DSL.name("delete_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.pet_mode.mode_name</code>.
     */
    public final TableField<PetModeRecord, String> MODE_NAME = createField(DSL.name("mode_name"), SQLDataType.VARCHAR(50), this, "");

    private PetMode(Name alias, Table<PetModeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PetMode(Name alias, Table<PetModeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.pet_mode</code> table reference
     */
    public PetMode(String alias) {
        this(DSL.name(alias), PET_MODE);
    }

    /**
     * Create an aliased <code>public.pet_mode</code> table reference
     */
    public PetMode(Name alias) {
        this(alias, PET_MODE);
    }

    /**
     * Create a <code>public.pet_mode</code> table reference
     */
    public PetMode() {
        this(DSL.name("pet_mode"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<PetModeRecord> getPrimaryKey() {
        return Keys.PET_MODE_PK;
    }

    @Override
    public PetMode as(String alias) {
        return new PetMode(DSL.name(alias), this);
    }

    @Override
    public PetMode as(Name alias) {
        return new PetMode(alias, this);
    }

    @Override
    public PetMode as(Table<?> alias) {
        return new PetMode(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PetMode rename(String name) {
        return new PetMode(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PetMode rename(Name name) {
        return new PetMode(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PetMode rename(Table<?> name) {
        return new PetMode(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PetMode where(Condition condition) {
        return new PetMode(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PetMode where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PetMode where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PetMode where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PetMode where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PetMode where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PetMode where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PetMode where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PetMode whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PetMode whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
