/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables;


import java.time.LocalDateTime;
import java.util.Collection;

import kr.co.common.jooq.Keys;
import kr.co.common.jooq.Public;
import kr.co.common.jooq.tables.Breed.BreedPath;
import kr.co.common.jooq.tables.records.SpeciesRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Species extends TableImpl<SpeciesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.species</code>
     */
    public static final Species SPECIES = new Species();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SpeciesRecord> getRecordType() {
        return SpeciesRecord.class;
    }

    /**
     * The column <code>public.species.species_id</code>.
     */
    public final TableField<SpeciesRecord, Integer> SPECIES_ID = createField(DSL.name("species_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.species.name</code>.
     */
    public final TableField<SpeciesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>public.species.create_date</code>.
     */
    public final TableField<SpeciesRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("create_date"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.species.create_user_id</code>.
     */
    public final TableField<SpeciesRecord, Long> CREATE_USER_ID = createField(DSL.name("create_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.species.update_date</code>.
     */
    public final TableField<SpeciesRecord, LocalDateTime> UPDATE_DATE = createField(DSL.name("update_date"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.species.update_user_id</code>.
     */
    public final TableField<SpeciesRecord, Long> UPDATE_USER_ID = createField(DSL.name("update_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.species.delete_date</code>.
     */
    public final TableField<SpeciesRecord, LocalDateTime> DELETE_DATE = createField(DSL.name("delete_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.species.delete_user_id</code>.
     */
    public final TableField<SpeciesRecord, Long> DELETE_USER_ID = createField(DSL.name("delete_user_id"), SQLDataType.BIGINT, this, "");

    private Species(Name alias, Table<SpeciesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Species(Name alias, Table<SpeciesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.species</code> table reference
     */
    public Species(String alias) {
        this(DSL.name(alias), SPECIES);
    }

    /**
     * Create an aliased <code>public.species</code> table reference
     */
    public Species(Name alias) {
        this(alias, SPECIES);
    }

    /**
     * Create a <code>public.species</code> table reference
     */
    public Species() {
        this(DSL.name("species"), null);
    }

    public <O extends Record> Species(Table<O> path, ForeignKey<O, SpeciesRecord> childPath, InverseForeignKey<O, SpeciesRecord> parentPath) {
        super(path, childPath, parentPath, SPECIES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SpeciesPath extends Species implements Path<SpeciesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SpeciesPath(Table<O> path, ForeignKey<O, SpeciesRecord> childPath, InverseForeignKey<O, SpeciesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SpeciesPath(Name alias, Table<SpeciesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SpeciesPath as(String alias) {
            return new SpeciesPath(DSL.name(alias), this);
        }

        @Override
        public SpeciesPath as(Name alias) {
            return new SpeciesPath(alias, this);
        }

        @Override
        public SpeciesPath as(Table<?> alias) {
            return new SpeciesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<SpeciesRecord> getPrimaryKey() {
        return Keys.SPECIES_PKEY;
    }

    private transient BreedPath _breed;

    /**
     * Get the implicit to-many join path to the <code>public.breed</code> table
     */
    public BreedPath breed() {
        if (_breed == null)
            _breed = new BreedPath(this, null, Keys.BREED__BREED_SPECIES_ID_FKEY.getInverseKey());

        return _breed;
    }

    @Override
    public Species as(String alias) {
        return new Species(DSL.name(alias), this);
    }

    @Override
    public Species as(Name alias) {
        return new Species(alias, this);
    }

    @Override
    public Species as(Table<?> alias) {
        return new Species(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Species rename(String name) {
        return new Species(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Species rename(Name name) {
        return new Species(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Species rename(Table<?> name) {
        return new Species(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Species where(Condition condition) {
        return new Species(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Species where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Species where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Species where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Species where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Species where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Species where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Species where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Species whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Species whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
