/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables;


import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import kr.co.common.jooq.Keys;
import kr.co.common.jooq.Public;
import kr.co.common.jooq.enums.UserLoginTypeEnum;
import kr.co.common.jooq.tables.Company.CompanyPath;
import kr.co.common.jooq.tables.EmailVerification.EmailVerificationPath;
import kr.co.common.jooq.tables.Pet.PetPath;
import kr.co.common.jooq.tables.Role.RolePath;
import kr.co.common.jooq.tables.records.UserRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class User extends TableImpl<UserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.user</code>
     */
    public static final User USER = new User();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserRecord> getRecordType() {
        return UserRecord.class;
    }

    /**
     * The column <code>public.user.user_id</code>.
     */
    public final TableField<UserRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.user.email</code>.
     */
    public final TableField<UserRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.user.user_uuid</code>.
     */
    public final TableField<UserRecord, String> USER_UUID = createField(DSL.name("user_uuid"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.user.password</code>.
     */
    public final TableField<UserRecord, String> PASSWORD = createField(DSL.name("password"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.user.role_id</code>.
     */
    public final TableField<UserRecord, Integer> ROLE_ID = createField(DSL.name("role_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.user.name</code>.
     */
    public final TableField<UserRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>public.user.nickname</code>.
     */
    public final TableField<UserRecord, String> NICKNAME = createField(DSL.name("nickname"), SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>public.user.phone_number</code>.
     */
    public final TableField<UserRecord, String> PHONE_NUMBER = createField(DSL.name("phone_number"), SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>public.user.birth_date</code>.
     */
    public final TableField<UserRecord, LocalDate> BIRTH_DATE = createField(DSL.name("birth_date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.user.gender</code>.
     */
    public final TableField<UserRecord, String> GENDER = createField(DSL.name("gender"), SQLDataType.CHAR(1), this, "");

    /**
     * The column <code>public.user.height</code>.
     */
    public final TableField<UserRecord, BigDecimal> HEIGHT = createField(DSL.name("height"), SQLDataType.NUMERIC(5, 2), this, "");

    /**
     * The column <code>public.user.weight</code>.
     */
    public final TableField<UserRecord, BigDecimal> WEIGHT = createField(DSL.name("weight"), SQLDataType.NUMERIC(5, 2), this, "");

    /**
     * The column <code>public.user.login_type</code>.
     */
    public final TableField<UserRecord, UserLoginTypeEnum> LOGIN_TYPE = createField(DSL.name("login_type"), SQLDataType.VARCHAR.asEnumDataType(UserLoginTypeEnum.class), this, "");

    /**
     * The column <code>public.user.login_id</code>.
     */
    public final TableField<UserRecord, String> LOGIN_ID = createField(DSL.name("login_id"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.user.is_email_verified</code>.
     */
    public final TableField<UserRecord, String> IS_EMAIL_VERIFIED = createField(DSL.name("is_email_verified"), SQLDataType.CHAR(1).defaultValue(DSL.field(DSL.raw("'N'::bpchar"), SQLDataType.CHAR)), this, "");

    /**
     * The column <code>public.user.company_id</code>.
     */
    public final TableField<UserRecord, Integer> COMPANY_ID = createField(DSL.name("company_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.user.description</code>.
     */
    public final TableField<UserRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>public.user.create_date</code>.
     */
    public final TableField<UserRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("create_date"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.user.create_user_id</code>.
     */
    public final TableField<UserRecord, Long> CREATE_USER_ID = createField(DSL.name("create_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.user.update_date</code>.
     */
    public final TableField<UserRecord, LocalDateTime> UPDATE_DATE = createField(DSL.name("update_date"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.user.update_user_id</code>.
     */
    public final TableField<UserRecord, Long> UPDATE_USER_ID = createField(DSL.name("update_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.user.delete_date</code>.
     */
    public final TableField<UserRecord, LocalDateTime> DELETE_DATE = createField(DSL.name("delete_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.user.is_phone_number_verified</code>.
     */
    public final TableField<UserRecord, String> IS_PHONE_NUMBER_VERIFIED = createField(DSL.name("is_phone_number_verified"), SQLDataType.CHAR(1).defaultValue(DSL.field(DSL.raw("'N'::bpchar"), SQLDataType.CHAR)), this, "");

    /**
     * The column <code>public.user.delete_user_id</code>.
     */
    public final TableField<UserRecord, Long> DELETE_USER_ID = createField(DSL.name("delete_user_id"), SQLDataType.BIGINT, this, "");

    private User(Name alias, Table<UserRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private User(Name alias, Table<UserRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.user</code> table reference
     */
    public User(String alias) {
        this(DSL.name(alias), USER);
    }

    /**
     * Create an aliased <code>public.user</code> table reference
     */
    public User(Name alias) {
        this(alias, USER);
    }

    /**
     * Create a <code>public.user</code> table reference
     */
    public User() {
        this(DSL.name("user"), null);
    }

    public <O extends Record> User(Table<O> path, ForeignKey<O, UserRecord> childPath, InverseForeignKey<O, UserRecord> parentPath) {
        super(path, childPath, parentPath, USER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UserPath extends User implements Path<UserRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UserPath(Table<O> path, ForeignKey<O, UserRecord> childPath, InverseForeignKey<O, UserRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private UserPath(Name alias, Table<UserRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public UserPath as(String alias) {
            return new UserPath(DSL.name(alias), this);
        }

        @Override
        public UserPath as(Name alias) {
            return new UserPath(alias, this);
        }

        @Override
        public UserPath as(Table<?> alias) {
            return new UserPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<UserRecord, Long> getIdentity() {
        return (Identity<UserRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<UserRecord> getPrimaryKey() {
        return Keys.USER_PKEY;
    }

    @Override
    public List<ForeignKey<UserRecord, ?>> getReferences() {
        return Arrays.asList(Keys.USER__USER_COMPANY_ID_FKEY, Keys.USER__USER_ROLE_ID_FKEY);
    }

    private transient CompanyPath _company;

    /**
     * Get the implicit join path to the <code>public.company</code> table.
     */
    public CompanyPath company() {
        if (_company == null)
            _company = new CompanyPath(this, Keys.USER__USER_COMPANY_ID_FKEY, null);

        return _company;
    }

    private transient RolePath _role;

    /**
     * Get the implicit join path to the <code>public.role</code> table.
     */
    public RolePath role() {
        if (_role == null)
            _role = new RolePath(this, Keys.USER__USER_ROLE_ID_FKEY, null);

        return _role;
    }

    private transient EmailVerificationPath _emailVerification;

    /**
     * Get the implicit to-many join path to the
     * <code>public.email_verification</code> table
     */
    public EmailVerificationPath emailVerification() {
        if (_emailVerification == null)
            _emailVerification = new EmailVerificationPath(this, null, Keys.EMAIL_VERIFICATION__FK_USER.getInverseKey());

        return _emailVerification;
    }

    private transient PetPath _pet;

    /**
     * Get the implicit to-many join path to the <code>public.pet</code> table
     */
    public PetPath pet() {
        if (_pet == null)
            _pet = new PetPath(this, null, Keys.PET__PET_USER_ID_FKEY.getInverseKey());

        return _pet;
    }

    @Override
    public User as(String alias) {
        return new User(DSL.name(alias), this);
    }

    @Override
    public User as(Name alias) {
        return new User(alias, this);
    }

    @Override
    public User as(Table<?> alias) {
        return new User(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public User rename(String name) {
        return new User(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public User rename(Name name) {
        return new User(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public User rename(Table<?> name) {
        return new User(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public User where(Condition condition) {
        return new User(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public User where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public User where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public User where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public User where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public User where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public User where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public User where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public User whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public User whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
