/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import kr.co.common.jooq.Keys;
import kr.co.common.jooq.Public;
import kr.co.common.jooq.tables.User.UserPath;
import kr.co.common.jooq.tables.records.UserVoteCountRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserVoteCount extends TableImpl<UserVoteCountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.user_vote_count</code>
     */
    public static final UserVoteCount USER_VOTE_COUNT = new UserVoteCount();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserVoteCountRecord> getRecordType() {
        return UserVoteCountRecord.class;
    }

    /**
     * The column <code>public.user_vote_count.user_id</code>.
     */
    public final TableField<UserVoteCountRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.user_vote_count.create_date</code>.
     */
    public final TableField<UserVoteCountRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("create_date"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.user_vote_count.create_user_id</code>.
     */
    public final TableField<UserVoteCountRecord, Long> CREATE_USER_ID = createField(DSL.name("create_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.user_vote_count.update_date</code>.
     */
    public final TableField<UserVoteCountRecord, LocalDateTime> UPDATE_DATE = createField(DSL.name("update_date"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.user_vote_count.update_user_id</code>.
     */
    public final TableField<UserVoteCountRecord, Long> UPDATE_USER_ID = createField(DSL.name("update_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.user_vote_count.vote_count</code>.
     */
    public final TableField<UserVoteCountRecord, Integer> VOTE_COUNT = createField(DSL.name("vote_count"), SQLDataType.INTEGER, this, "");

    private UserVoteCount(Name alias, Table<UserVoteCountRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserVoteCount(Name alias, Table<UserVoteCountRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.user_vote_count</code> table reference
     */
    public UserVoteCount(String alias) {
        this(DSL.name(alias), USER_VOTE_COUNT);
    }

    /**
     * Create an aliased <code>public.user_vote_count</code> table reference
     */
    public UserVoteCount(Name alias) {
        this(alias, USER_VOTE_COUNT);
    }

    /**
     * Create a <code>public.user_vote_count</code> table reference
     */
    public UserVoteCount() {
        this(DSL.name("user_vote_count"), null);
    }

    public <O extends Record> UserVoteCount(Table<O> path, ForeignKey<O, UserVoteCountRecord> childPath, InverseForeignKey<O, UserVoteCountRecord> parentPath) {
        super(path, childPath, parentPath, USER_VOTE_COUNT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UserVoteCountPath extends UserVoteCount implements Path<UserVoteCountRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UserVoteCountPath(Table<O> path, ForeignKey<O, UserVoteCountRecord> childPath, InverseForeignKey<O, UserVoteCountRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private UserVoteCountPath(Name alias, Table<UserVoteCountRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public UserVoteCountPath as(String alias) {
            return new UserVoteCountPath(DSL.name(alias), this);
        }

        @Override
        public UserVoteCountPath as(Name alias) {
            return new UserVoteCountPath(alias, this);
        }

        @Override
        public UserVoteCountPath as(Table<?> alias) {
            return new UserVoteCountPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<UserVoteCountRecord, Long> getIdentity() {
        return (Identity<UserVoteCountRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<UserVoteCountRecord> getPrimaryKey() {
        return Keys.USER_VOTE_COUNT_PK;
    }

    @Override
    public List<ForeignKey<UserVoteCountRecord, ?>> getReferences() {
        return Arrays.asList(Keys.USER_VOTE_COUNT__USER_VOTE_COUNT_USER_FK);
    }

    private transient UserPath _user;

    /**
     * Get the implicit join path to the <code>public.user</code> table.
     */
    public UserPath user() {
        if (_user == null)
            _user = new UserPath(this, Keys.USER_VOTE_COUNT__USER_VOTE_COUNT_USER_FK, null);

        return _user;
    }

    @Override
    public UserVoteCount as(String alias) {
        return new UserVoteCount(DSL.name(alias), this);
    }

    @Override
    public UserVoteCount as(Name alias) {
        return new UserVoteCount(alias, this);
    }

    @Override
    public UserVoteCount as(Table<?> alias) {
        return new UserVoteCount(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserVoteCount rename(String name) {
        return new UserVoteCount(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserVoteCount rename(Name name) {
        return new UserVoteCount(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserVoteCount rename(Table<?> name) {
        return new UserVoteCount(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserVoteCount where(Condition condition) {
        return new UserVoteCount(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserVoteCount where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserVoteCount where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserVoteCount where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserVoteCount where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserVoteCount where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserVoteCount where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserVoteCount where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserVoteCount whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserVoteCount whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
