/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import kr.co.common.jooq.Keys;
import kr.co.common.jooq.Public;
import kr.co.common.jooq.tables.User.UserPath;
import kr.co.common.jooq.tables.records.UserVoteCountHistoryRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserVoteCountHistory extends TableImpl<UserVoteCountHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.user_vote_count_history</code>
     */
    public static final UserVoteCountHistory USER_VOTE_COUNT_HISTORY = new UserVoteCountHistory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserVoteCountHistoryRecord> getRecordType() {
        return UserVoteCountHistoryRecord.class;
    }

    /**
     * The column <code>public.user_vote_count_history.history_id</code>.
     */
    public final TableField<UserVoteCountHistoryRecord, Long> HISTORY_ID = createField(DSL.name("history_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.user_vote_count_history.create_date</code>.
     */
    public final TableField<UserVoteCountHistoryRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("create_date"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.user_vote_count_history.create_user_id</code>.
     */
    public final TableField<UserVoteCountHistoryRecord, Long> CREATE_USER_ID = createField(DSL.name("create_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.user_vote_count_history.user_id</code>.
     */
    public final TableField<UserVoteCountHistoryRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.user_vote_count_history.change_amount</code>.
     */
    public final TableField<UserVoteCountHistoryRecord, Integer> CHANGE_AMOUNT = createField(DSL.name("change_amount"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.user_vote_count_history.before_count</code>.
     */
    public final TableField<UserVoteCountHistoryRecord, Integer> BEFORE_COUNT = createField(DSL.name("before_count"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.user_vote_count_history.after_count</code>.
     */
    public final TableField<UserVoteCountHistoryRecord, Integer> AFTER_COUNT = createField(DSL.name("after_count"), SQLDataType.INTEGER.nullable(false), this, "");

    private UserVoteCountHistory(Name alias, Table<UserVoteCountHistoryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserVoteCountHistory(Name alias, Table<UserVoteCountHistoryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.user_vote_count_history</code> table
     * reference
     */
    public UserVoteCountHistory(String alias) {
        this(DSL.name(alias), USER_VOTE_COUNT_HISTORY);
    }

    /**
     * Create an aliased <code>public.user_vote_count_history</code> table
     * reference
     */
    public UserVoteCountHistory(Name alias) {
        this(alias, USER_VOTE_COUNT_HISTORY);
    }

    /**
     * Create a <code>public.user_vote_count_history</code> table reference
     */
    public UserVoteCountHistory() {
        this(DSL.name("user_vote_count_history"), null);
    }

    public <O extends Record> UserVoteCountHistory(Table<O> path, ForeignKey<O, UserVoteCountHistoryRecord> childPath, InverseForeignKey<O, UserVoteCountHistoryRecord> parentPath) {
        super(path, childPath, parentPath, USER_VOTE_COUNT_HISTORY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UserVoteCountHistoryPath extends UserVoteCountHistory implements Path<UserVoteCountHistoryRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UserVoteCountHistoryPath(Table<O> path, ForeignKey<O, UserVoteCountHistoryRecord> childPath, InverseForeignKey<O, UserVoteCountHistoryRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private UserVoteCountHistoryPath(Name alias, Table<UserVoteCountHistoryRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public UserVoteCountHistoryPath as(String alias) {
            return new UserVoteCountHistoryPath(DSL.name(alias), this);
        }

        @Override
        public UserVoteCountHistoryPath as(Name alias) {
            return new UserVoteCountHistoryPath(alias, this);
        }

        @Override
        public UserVoteCountHistoryPath as(Table<?> alias) {
            return new UserVoteCountHistoryPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<UserVoteCountHistoryRecord, Long> getIdentity() {
        return (Identity<UserVoteCountHistoryRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<UserVoteCountHistoryRecord> getPrimaryKey() {
        return Keys.USER_VOTE_COUNT_HISTORY_PK;
    }

    @Override
    public List<ForeignKey<UserVoteCountHistoryRecord, ?>> getReferences() {
        return Arrays.asList(Keys.USER_VOTE_COUNT_HISTORY__USER_VOTE_COUNT_HISTORY_USER_FK);
    }

    private transient UserPath _user;

    /**
     * Get the implicit join path to the <code>public.user</code> table.
     */
    public UserPath user() {
        if (_user == null)
            _user = new UserPath(this, Keys.USER_VOTE_COUNT_HISTORY__USER_VOTE_COUNT_HISTORY_USER_FK, null);

        return _user;
    }

    @Override
    public UserVoteCountHistory as(String alias) {
        return new UserVoteCountHistory(DSL.name(alias), this);
    }

    @Override
    public UserVoteCountHistory as(Name alias) {
        return new UserVoteCountHistory(alias, this);
    }

    @Override
    public UserVoteCountHistory as(Table<?> alias) {
        return new UserVoteCountHistory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserVoteCountHistory rename(String name) {
        return new UserVoteCountHistory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserVoteCountHistory rename(Name name) {
        return new UserVoteCountHistory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserVoteCountHistory rename(Table<?> name) {
        return new UserVoteCountHistory(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserVoteCountHistory where(Condition condition) {
        return new UserVoteCountHistory(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserVoteCountHistory where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserVoteCountHistory where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserVoteCountHistory where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserVoteCountHistory where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserVoteCountHistory where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserVoteCountHistory where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserVoteCountHistory where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserVoteCountHistory whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserVoteCountHistory whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
