/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables;


import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Collection;

import kr.co.common.jooq.Keys;
import kr.co.common.jooq.Public;
import kr.co.common.jooq.tables.records.VoteWeeklyRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VoteWeekly extends TableImpl<VoteWeeklyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.vote_weekly</code>
     */
    public static final VoteWeekly VOTE_WEEKLY = new VoteWeekly();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VoteWeeklyRecord> getRecordType() {
        return VoteWeeklyRecord.class;
    }

    /**
     * The column <code>public.vote_weekly.vote_weekly_id</code>.
     */
    public final TableField<VoteWeeklyRecord, Long> VOTE_WEEKLY_ID = createField(DSL.name("vote_weekly_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.vote_weekly.create_date</code>.
     */
    public final TableField<VoteWeeklyRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("create_date"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.vote_weekly.create_user_id</code>.
     */
    public final TableField<VoteWeeklyRecord, Long> CREATE_USER_ID = createField(DSL.name("create_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.vote_weekly.update_date</code>.
     */
    public final TableField<VoteWeeklyRecord, LocalDateTime> UPDATE_DATE = createField(DSL.name("update_date"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.vote_weekly.update_user_id</code>.
     */
    public final TableField<VoteWeeklyRecord, Long> UPDATE_USER_ID = createField(DSL.name("update_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.vote_weekly.delete_date</code>.
     */
    public final TableField<VoteWeeklyRecord, LocalDateTime> DELETE_DATE = createField(DSL.name("delete_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.vote_weekly.delete_user_id</code>.
     */
    public final TableField<VoteWeeklyRecord, Long> DELETE_USER_ID = createField(DSL.name("delete_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.vote_weekly.week_start_date</code>.
     */
    public final TableField<VoteWeeklyRecord, LocalDate> WEEK_START_DATE = createField(DSL.name("week_start_date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>public.vote_weekly.pet_id</code>.
     */
    public final TableField<VoteWeeklyRecord, Long> PET_ID = createField(DSL.name("pet_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.vote_weekly.vote_count</code>.
     */
    public final TableField<VoteWeeklyRecord, Integer> VOTE_COUNT = createField(DSL.name("vote_count"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.vote_weekly.view_count</code>.
     */
    public final TableField<VoteWeeklyRecord, Long> VIEW_COUNT = createField(DSL.name("view_count"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.vote_weekly.mode_id</code>.
     */
    public final TableField<VoteWeeklyRecord, Integer> MODE_ID = createField(DSL.name("mode_id"), SQLDataType.INTEGER, this, "");

    private VoteWeekly(Name alias, Table<VoteWeeklyRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VoteWeekly(Name alias, Table<VoteWeeklyRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.vote_weekly</code> table reference
     */
    public VoteWeekly(String alias) {
        this(DSL.name(alias), VOTE_WEEKLY);
    }

    /**
     * Create an aliased <code>public.vote_weekly</code> table reference
     */
    public VoteWeekly(Name alias) {
        this(alias, VOTE_WEEKLY);
    }

    /**
     * Create a <code>public.vote_weekly</code> table reference
     */
    public VoteWeekly() {
        this(DSL.name("vote_weekly"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<VoteWeeklyRecord, Long> getIdentity() {
        return (Identity<VoteWeeklyRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<VoteWeeklyRecord> getPrimaryKey() {
        return Keys.WEEKLY_VOTE_PKEY;
    }

    @Override
    public VoteWeekly as(String alias) {
        return new VoteWeekly(DSL.name(alias), this);
    }

    @Override
    public VoteWeekly as(Name alias) {
        return new VoteWeekly(alias, this);
    }

    @Override
    public VoteWeekly as(Table<?> alias) {
        return new VoteWeekly(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VoteWeekly rename(String name) {
        return new VoteWeekly(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VoteWeekly rename(Name name) {
        return new VoteWeekly(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VoteWeekly rename(Table<?> name) {
        return new VoteWeekly(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VoteWeekly where(Condition condition) {
        return new VoteWeekly(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VoteWeekly where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VoteWeekly where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VoteWeekly where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VoteWeekly where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VoteWeekly where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VoteWeekly where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VoteWeekly where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VoteWeekly whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VoteWeekly whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
