/*
 * This file is generated by jOOQ.
 */
package kr.co.common.jooq.tables;


import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import kr.co.common.jooq.Keys;
import kr.co.common.jooq.Public;
import kr.co.common.jooq.enums.VoteCycleType;
import kr.co.common.jooq.tables.records.VoteHistoryRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VoteHistory extends TableImpl<VoteHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.vote_history</code>
     */
    public static final VoteHistory VOTE_HISTORY = new VoteHistory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VoteHistoryRecord> getRecordType() {
        return VoteHistoryRecord.class;
    }

    /**
     * The column <code>public.vote_history.vote_history_id</code>.
     */
    public final TableField<VoteHistoryRecord, Long> VOTE_HISTORY_ID = createField(DSL.name("vote_history_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.vote_history.create_date</code>.
     */
    public final TableField<VoteHistoryRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("create_date"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.vote_history.user_id</code>.
     */
    public final TableField<VoteHistoryRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.vote_history.vote_id</code>.
     */
    public final TableField<VoteHistoryRecord, Long> VOTE_ID = createField(DSL.name("vote_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.vote_history.history_date</code>.
     */
    public final TableField<VoteHistoryRecord, LocalDate> HISTORY_DATE = createField(DSL.name("history_date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>public.vote_history.email</code>.
     */
    public final TableField<VoteHistoryRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.vote_history.vote_cycle</code>.
     */
    public final TableField<VoteHistoryRecord, VoteCycleType> VOTE_CYCLE = createField(DSL.name("vote_cycle"), SQLDataType.VARCHAR.asEnumDataType(VoteCycleType.class), this, "");

    private VoteHistory(Name alias, Table<VoteHistoryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VoteHistory(Name alias, Table<VoteHistoryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.vote_history</code> table reference
     */
    public VoteHistory(String alias) {
        this(DSL.name(alias), VOTE_HISTORY);
    }

    /**
     * Create an aliased <code>public.vote_history</code> table reference
     */
    public VoteHistory(Name alias) {
        this(alias, VOTE_HISTORY);
    }

    /**
     * Create a <code>public.vote_history</code> table reference
     */
    public VoteHistory() {
        this(DSL.name("vote_history"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<VoteHistoryRecord, Long> getIdentity() {
        return (Identity<VoteHistoryRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<VoteHistoryRecord> getPrimaryKey() {
        return Keys.VOTE_HISTORY_PK;
    }

    @Override
    public List<UniqueKey<VoteHistoryRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.VOTE_HISTORY_UNIQUE, Keys.VOTE_HISTORY_UNIQUE_1);
    }

    @Override
    public VoteHistory as(String alias) {
        return new VoteHistory(DSL.name(alias), this);
    }

    @Override
    public VoteHistory as(Name alias) {
        return new VoteHistory(alias, this);
    }

    @Override
    public VoteHistory as(Table<?> alias) {
        return new VoteHistory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VoteHistory rename(String name) {
        return new VoteHistory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VoteHistory rename(Name name) {
        return new VoteHistory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VoteHistory rename(Table<?> name) {
        return new VoteHistory(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VoteHistory where(Condition condition) {
        return new VoteHistory(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VoteHistory where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VoteHistory where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VoteHistory where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VoteHistory where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VoteHistory where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VoteHistory where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VoteHistory where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VoteHistory whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VoteHistory whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
